package com.teradata.portal.admin.subscribe.pojo;

import com.teradata.portal.admin.subscribe.common.BaseInfo;

public class ApiRssInfo extends BaseInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.rss_id
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private Integer rssId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.rss_start_time
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private Long rssStartTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.rss_end_time
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private Long rssEndTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.appkey
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private String appkey;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.api_id
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private Integer apiId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.api_version
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private Integer apiVersion;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.api_name
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private String apiName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.api_sort
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private Integer apiSort;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.api_sort_name
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private String apiSortName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.api_cls_code
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private Integer apiClsCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.api_cls_desc
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private String apiClsDesc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.data_cycle_type
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private Integer dataCycleType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.data_cycle_desc
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private String dataCycleDesc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.form_code
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private String formCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.encode
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private String encode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.req_arg
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private String reqArg;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.req_arg_render
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private String reqArgRender;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.respn_arg
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private String respnArg;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.respn_arg_render
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private String respnArgRender;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.push_arg
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private String pushArg;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.push_arg_render
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private String pushArgRender;

	private FtpUseInfo ftpUseInfo;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.retn_form_finger
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private String retnFormFinger;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.retn_data_finger
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private String retnDataFinger;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.trigger_methd
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private Integer triggerMethd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.trigger_methd_desc
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private String triggerMethdDesc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.trigger_sorc
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private String triggerSorc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.priority
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private Integer priority;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.eff_flag
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private Integer effFlag;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_rss_info_vw.eff_desc
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	private String effDesc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_rss_info_vw.rss_id
	 * 
	 * @return the value of opi.api_rss_info_vw.rss_id
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public Integer getRssId() {
		return rssId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_rss_info_vw.rss_id
	 * 
	 * @param rssId the value for opi.api_rss_info_vw.rss_id
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setRssId(Integer rssId) {
		this.rssId = rssId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * opi.api_rss_info_vw.rss_start_time
	 * 
	 * @return the value of opi.api_rss_info_vw.rss_start_time
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public Long getRssStartTime() {
		return rssStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_rss_info_vw.rss_start_time
	 * 
	 * @param rssStartTime the value for opi.api_rss_info_vw.rss_start_time
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setRssStartTime(Long rssStartTime) {
		this.rssStartTime = rssStartTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_rss_info_vw.rss_end_time
	 * 
	 * @return the value of opi.api_rss_info_vw.rss_end_time
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public Long getRssEndTime() {
		return rssEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_rss_info_vw.rss_end_time
	 * 
	 * @param rssEndTime the value for opi.api_rss_info_vw.rss_end_time
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setRssEndTime(Long rssEndTime) {
		this.rssEndTime = rssEndTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_rss_info_vw.appkey
	 * 
	 * @return the value of opi.api_rss_info_vw.appkey
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public String getAppkey() {
		return appkey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_rss_info_vw.appkey
	 * 
	 * @param appkey the value for opi.api_rss_info_vw.appkey
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setAppkey(String appkey) {
		this.appkey = appkey == null ? null : appkey.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_rss_info_vw.api_id
	 * 
	 * @return the value of opi.api_rss_info_vw.api_id
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public Integer getApiId() {
		return apiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_rss_info_vw.api_id
	 * 
	 * @param apiId the value for opi.api_rss_info_vw.api_id
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setApiId(Integer apiId) {
		this.apiId = apiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_rss_info_vw.api_version
	 * 
	 * @return the value of opi.api_rss_info_vw.api_version
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public Integer getApiVersion() {
		return apiVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_rss_info_vw.api_version
	 * 
	 * @param apiVersion the value for opi.api_rss_info_vw.api_version
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setApiVersion(Integer apiVersion) {
		this.apiVersion = apiVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_rss_info_vw.api_name
	 * 
	 * @return the value of opi.api_rss_info_vw.api_name
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public String getApiName() {
		return apiName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_rss_info_vw.api_name
	 * 
	 * @param apiName the value for opi.api_rss_info_vw.api_name
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setApiName(String apiName) {
		this.apiName = apiName == null ? null : apiName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_rss_info_vw.api_sort
	 * 
	 * @return the value of opi.api_rss_info_vw.api_sort
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public Integer getApiSort() {
		return apiSort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_rss_info_vw.api_sort
	 * 
	 * @param apiSort the value for opi.api_rss_info_vw.api_sort
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setApiSort(Integer apiSort) {
		this.apiSort = apiSort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * opi.api_rss_info_vw.api_sort_name
	 * 
	 * @return the value of opi.api_rss_info_vw.api_sort_name
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public String getApiSortName() {
		return apiSortName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_rss_info_vw.api_sort_name
	 * 
	 * @param apiSortName the value for opi.api_rss_info_vw.api_sort_name
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setApiSortName(String apiSortName) {
		this.apiSortName = apiSortName == null ? null : apiSortName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_rss_info_vw.api_cls_code
	 * 
	 * @return the value of opi.api_rss_info_vw.api_cls_code
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public Integer getApiClsCode() {
		return apiClsCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_rss_info_vw.api_cls_code
	 * 
	 * @param apiClsCode the value for opi.api_rss_info_vw.api_cls_code
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setApiClsCode(Integer apiClsCode) {
		this.apiClsCode = apiClsCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_rss_info_vw.api_cls_desc
	 * 
	 * @return the value of opi.api_rss_info_vw.api_cls_desc
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public String getApiClsDesc() {
		return apiClsDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_rss_info_vw.api_cls_desc
	 * 
	 * @param apiClsDesc the value for opi.api_rss_info_vw.api_cls_desc
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setApiClsDesc(String apiClsDesc) {
		this.apiClsDesc = apiClsDesc == null ? null : apiClsDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * opi.api_rss_info_vw.data_cycle_type
	 * 
	 * @return the value of opi.api_rss_info_vw.data_cycle_type
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public Integer getDataCycleType() {
		return dataCycleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_rss_info_vw.data_cycle_type
	 * 
	 * @param dataCycleType the value for opi.api_rss_info_vw.data_cycle_type
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setDataCycleType(Integer dataCycleType) {
		this.dataCycleType = dataCycleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * opi.api_rss_info_vw.data_cycle_desc
	 * 
	 * @return the value of opi.api_rss_info_vw.data_cycle_desc
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public String getDataCycleDesc() {
		return dataCycleDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_rss_info_vw.data_cycle_desc
	 * 
	 * @param dataCycleDesc the value for opi.api_rss_info_vw.data_cycle_desc
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setDataCycleDesc(String dataCycleDesc) {
		this.dataCycleDesc = dataCycleDesc == null ? null : dataCycleDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_rss_info_vw.form_code
	 * 
	 * @return the value of opi.api_rss_info_vw.form_code
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public String getFormCode() {
		return formCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_rss_info_vw.form_code
	 * 
	 * @param formCode the value for opi.api_rss_info_vw.form_code
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setFormCode(String formCode) {
		this.formCode = formCode == null ? null : formCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_rss_info_vw.encode
	 * 
	 * @return the value of opi.api_rss_info_vw.encode
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public String getEncode() {
		return encode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_rss_info_vw.encode
	 * 
	 * @param encode the value for opi.api_rss_info_vw.encode
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setEncode(String encode) {
		this.encode = encode == null ? null : encode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_rss_info_vw.req_arg
	 * 
	 * @return the value of opi.api_rss_info_vw.req_arg
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public String getReqArg() {
		return reqArg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_rss_info_vw.req_arg
	 * 
	 * @param reqArg the value for opi.api_rss_info_vw.req_arg
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setReqArg(String reqArg) {
		this.reqArg = reqArg == null ? null : reqArg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * opi.api_rss_info_vw.req_arg_render
	 * 
	 * @return the value of opi.api_rss_info_vw.req_arg_render
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public String getReqArgRender() {
		return reqArgRender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_rss_info_vw.req_arg_render
	 * 
	 * @param reqArgRender the value for opi.api_rss_info_vw.req_arg_render
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setReqArgRender(String reqArgRender) {
		this.reqArgRender = reqArgRender == null ? null : reqArgRender.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_rss_info_vw.respn_arg
	 * 
	 * @return the value of opi.api_rss_info_vw.respn_arg
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public String getRespnArg() {
		return respnArg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_rss_info_vw.respn_arg
	 * 
	 * @param respnArg the value for opi.api_rss_info_vw.respn_arg
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setRespnArg(String respnArg) {
		this.respnArg = respnArg == null ? null : respnArg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * opi.api_rss_info_vw.respn_arg_render
	 * 
	 * @return the value of opi.api_rss_info_vw.respn_arg_render
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public String getRespnArgRender() {
		return respnArgRender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * opi.api_rss_info_vw.respn_arg_render
	 * 
	 * @param respnArgRender the value for opi.api_rss_info_vw.respn_arg_render
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setRespnArgRender(String respnArgRender) {
		this.respnArgRender = respnArgRender == null ? null : respnArgRender.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_rss_info_vw.push_arg
	 * 
	 * @return the value of opi.api_rss_info_vw.push_arg
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public String getPushArg() {
		return pushArg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_rss_info_vw.push_arg
	 * 
	 * @param pushArg the value for opi.api_rss_info_vw.push_arg
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setPushArg(String pushArg) {
		this.pushArg = pushArg == null ? null : pushArg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * opi.api_rss_info_vw.push_arg_render
	 * 
	 * @return the value of opi.api_rss_info_vw.push_arg_render
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public String getPushArgRender() {
		return pushArgRender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_rss_info_vw.push_arg_render
	 * 
	 * @param pushArgRender the value for opi.api_rss_info_vw.push_arg_render
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setPushArgRender(String pushArgRender) {
		this.pushArgRender = pushArgRender == null ? null : pushArgRender.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * opi.api_rss_info_vw.retn_form_finger
	 * 
	 * @return the value of opi.api_rss_info_vw.retn_form_finger
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public String getRetnFormFinger() {
		return retnFormFinger;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * opi.api_rss_info_vw.retn_form_finger
	 * 
	 * @param retnFormFinger the value for opi.api_rss_info_vw.retn_form_finger
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setRetnFormFinger(String retnFormFinger) {
		this.retnFormFinger = retnFormFinger == null ? null : retnFormFinger.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * opi.api_rss_info_vw.retn_data_finger
	 * 
	 * @return the value of opi.api_rss_info_vw.retn_data_finger
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public String getRetnDataFinger() {
		return retnDataFinger;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * opi.api_rss_info_vw.retn_data_finger
	 * 
	 * @param retnDataFinger the value for opi.api_rss_info_vw.retn_data_finger
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setRetnDataFinger(String retnDataFinger) {
		this.retnDataFinger = retnDataFinger == null ? null : retnDataFinger.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * opi.api_rss_info_vw.trigger_methd
	 * 
	 * @return the value of opi.api_rss_info_vw.trigger_methd
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public Integer getTriggerMethd() {
		return triggerMethd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_rss_info_vw.trigger_methd
	 * 
	 * @param triggerMethd the value for opi.api_rss_info_vw.trigger_methd
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setTriggerMethd(Integer triggerMethd) {
		this.triggerMethd = triggerMethd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * opi.api_rss_info_vw.trigger_methd_desc
	 * 
	 * @return the value of opi.api_rss_info_vw.trigger_methd_desc
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public String getTriggerMethdDesc() {
		return triggerMethdDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * opi.api_rss_info_vw.trigger_methd_desc
	 * 
	 * @param triggerMethdDesc the value for opi.api_rss_info_vw.trigger_methd_desc
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setTriggerMethdDesc(String triggerMethdDesc) {
		this.triggerMethdDesc = triggerMethdDesc == null ? null : triggerMethdDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_rss_info_vw.trigger_sorc
	 * 
	 * @return the value of opi.api_rss_info_vw.trigger_sorc
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public String getTriggerSorc() {
		return triggerSorc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_rss_info_vw.trigger_sorc
	 * 
	 * @param triggerSorc the value for opi.api_rss_info_vw.trigger_sorc
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setTriggerSorc(String triggerSorc) {
		this.triggerSorc = triggerSorc == null ? null : triggerSorc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_rss_info_vw.priority
	 * 
	 * @return the value of opi.api_rss_info_vw.priority
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public Integer getPriority() {
		return priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_rss_info_vw.priority
	 * 
	 * @param priority the value for opi.api_rss_info_vw.priority
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_rss_info_vw.eff_flag
	 * 
	 * @return the value of opi.api_rss_info_vw.eff_flag
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public Integer getEffFlag() {
		return effFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_rss_info_vw.eff_flag
	 * 
	 * @param effFlag the value for opi.api_rss_info_vw.eff_flag
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setEffFlag(Integer effFlag) {
		this.effFlag = effFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_rss_info_vw.eff_desc
	 * 
	 * @return the value of opi.api_rss_info_vw.eff_desc
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public String getEffDesc() {
		return effDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_rss_info_vw.eff_desc
	 * 
	 * @param effDesc the value for opi.api_rss_info_vw.eff_desc
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setEffDesc(String effDesc) {
		this.effDesc = effDesc == null ? null : effDesc.trim();
	}

	public FtpUseInfo getFtpUseInfo() {
		return ftpUseInfo;
	}

	public void setFtpUseInfo(FtpUseInfo ftpUseInfo) {
		this.ftpUseInfo = ftpUseInfo;
	}

}