package com.teradata.portal.admin.subscribe.pojo;

import java.util.ArrayList;
import java.util.List;

public class ApiRssInfoExample {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table opi.api_rss_info_vw
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table opi.api_rss_info_vw
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table opi.api_rss_info_vw
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opi.api_rss_info_vw
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public ApiRssInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opi.api_rss_info_vw
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opi.api_rss_info_vw
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opi.api_rss_info_vw
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opi.api_rss_info_vw
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opi.api_rss_info_vw
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opi.api_rss_info_vw
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opi.api_rss_info_vw
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opi.api_rss_info_vw
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opi.api_rss_info_vw
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opi.api_rss_info_vw
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table opi.api_rss_info_vw
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	protected abstract static class GeneratedCriteria {

		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andRssIdIsNull() {
			addCriterion("rss_id is null");
			return (Criteria) this;
		}

		public Criteria andRssIdIsNotNull() {
			addCriterion("rss_id is not null");
			return (Criteria) this;
		}

		public Criteria andRssIdEqualTo(Integer value) {
			addCriterion("rss_id =", value, "rssId");
			return (Criteria) this;
		}

		public Criteria andRssIdNotEqualTo(Integer value) {
			addCriterion("rss_id <>", value, "rssId");
			return (Criteria) this;
		}

		public Criteria andRssIdGreaterThan(Integer value) {
			addCriterion("rss_id >", value, "rssId");
			return (Criteria) this;
		}

		public Criteria andRssIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("rss_id >=", value, "rssId");
			return (Criteria) this;
		}

		public Criteria andRssIdLessThan(Integer value) {
			addCriterion("rss_id <", value, "rssId");
			return (Criteria) this;
		}

		public Criteria andRssIdLessThanOrEqualTo(Integer value) {
			addCriterion("rss_id <=", value, "rssId");
			return (Criteria) this;
		}

		public Criteria andRssIdIn(List<Integer> values) {
			addCriterion("rss_id in", values, "rssId");
			return (Criteria) this;
		}

		public Criteria andRssIdNotIn(List<Integer> values) {
			addCriterion("rss_id not in", values, "rssId");
			return (Criteria) this;
		}

		public Criteria andRssIdBetween(Integer value1, Integer value2) {
			addCriterion("rss_id between", value1, value2, "rssId");
			return (Criteria) this;
		}

		public Criteria andRssIdNotBetween(Integer value1, Integer value2) {
			addCriterion("rss_id not between", value1, value2, "rssId");
			return (Criteria) this;
		}

		public Criteria andRssStartTimeIsNull() {
			addCriterion("rss_start_time is null");
			return (Criteria) this;
		}

		public Criteria andRssStartTimeIsNotNull() {
			addCriterion("rss_start_time is not null");
			return (Criteria) this;
		}

		public Criteria andRssStartTimeEqualTo(Long value) {
			addCriterion("rss_start_time =", value, "rssStartTime");
			return (Criteria) this;
		}

		public Criteria andRssStartTimeNotEqualTo(Long value) {
			addCriterion("rss_start_time <>", value, "rssStartTime");
			return (Criteria) this;
		}

		public Criteria andRssStartTimeGreaterThan(Long value) {
			addCriterion("rss_start_time >", value, "rssStartTime");
			return (Criteria) this;
		}

		public Criteria andRssStartTimeGreaterThanOrEqualTo(Long value) {
			addCriterion("rss_start_time >=", value, "rssStartTime");
			return (Criteria) this;
		}

		public Criteria andRssStartTimeLessThan(Long value) {
			addCriterion("rss_start_time <", value, "rssStartTime");
			return (Criteria) this;
		}

		public Criteria andRssStartTimeLessThanOrEqualTo(Long value) {
			addCriterion("rss_start_time <=", value, "rssStartTime");
			return (Criteria) this;
		}

		public Criteria andRssStartTimeIn(List<Long> values) {
			addCriterion("rss_start_time in", values, "rssStartTime");
			return (Criteria) this;
		}

		public Criteria andRssStartTimeNotIn(List<Long> values) {
			addCriterion("rss_start_time not in", values, "rssStartTime");
			return (Criteria) this;
		}

		public Criteria andRssStartTimeBetween(Long value1, Long value2) {
			addCriterion("rss_start_time between", value1, value2, "rssStartTime");
			return (Criteria) this;
		}

		public Criteria andRssStartTimeNotBetween(Long value1, Long value2) {
			addCriterion("rss_start_time not between", value1, value2, "rssStartTime");
			return (Criteria) this;
		}

		public Criteria andRssEndTimeIsNull() {
			addCriterion("rss_end_time is null");
			return (Criteria) this;
		}

		public Criteria andRssEndTimeIsNotNull() {
			addCriterion("rss_end_time is not null");
			return (Criteria) this;
		}

		public Criteria andRssEndTimeEqualTo(Long value) {
			addCriterion("rss_end_time =", value, "rssEndTime");
			return (Criteria) this;
		}

		public Criteria andRssEndTimeNotEqualTo(Long value) {
			addCriterion("rss_end_time <>", value, "rssEndTime");
			return (Criteria) this;
		}

		public Criteria andRssEndTimeGreaterThan(Long value) {
			addCriterion("rss_end_time >", value, "rssEndTime");
			return (Criteria) this;
		}

		public Criteria andRssEndTimeGreaterThanOrEqualTo(Long value) {
			addCriterion("rss_end_time >=", value, "rssEndTime");
			return (Criteria) this;
		}

		public Criteria andRssEndTimeLessThan(Long value) {
			addCriterion("rss_end_time <", value, "rssEndTime");
			return (Criteria) this;
		}

		public Criteria andRssEndTimeLessThanOrEqualTo(Long value) {
			addCriterion("rss_end_time <=", value, "rssEndTime");
			return (Criteria) this;
		}

		public Criteria andRssEndTimeIn(List<Long> values) {
			addCriterion("rss_end_time in", values, "rssEndTime");
			return (Criteria) this;
		}

		public Criteria andRssEndTimeNotIn(List<Long> values) {
			addCriterion("rss_end_time not in", values, "rssEndTime");
			return (Criteria) this;
		}

		public Criteria andRssEndTimeBetween(Long value1, Long value2) {
			addCriterion("rss_end_time between", value1, value2, "rssEndTime");
			return (Criteria) this;
		}

		public Criteria andRssEndTimeNotBetween(Long value1, Long value2) {
			addCriterion("rss_end_time not between", value1, value2, "rssEndTime");
			return (Criteria) this;
		}

		public Criteria andAppkeyIsNull() {
			addCriterion("appkey is null");
			return (Criteria) this;
		}

		public Criteria andAppkeyIsNotNull() {
			addCriterion("appkey is not null");
			return (Criteria) this;
		}

		public Criteria andAppkeyEqualTo(String value) {
			addCriterion("appkey =", value, "appkey");
			return (Criteria) this;
		}

		public Criteria andAppkeyNotEqualTo(String value) {
			addCriterion("appkey <>", value, "appkey");
			return (Criteria) this;
		}

		public Criteria andAppkeyGreaterThan(String value) {
			addCriterion("appkey >", value, "appkey");
			return (Criteria) this;
		}

		public Criteria andAppkeyGreaterThanOrEqualTo(String value) {
			addCriterion("appkey >=", value, "appkey");
			return (Criteria) this;
		}

		public Criteria andAppkeyLessThan(String value) {
			addCriterion("appkey <", value, "appkey");
			return (Criteria) this;
		}

		public Criteria andAppkeyLessThanOrEqualTo(String value) {
			addCriterion("appkey <=", value, "appkey");
			return (Criteria) this;
		}

		public Criteria andAppkeyLike(String value) {
			addCriterion("appkey like", value, "appkey");
			return (Criteria) this;
		}

		public Criteria andAppkeyNotLike(String value) {
			addCriterion("appkey not like", value, "appkey");
			return (Criteria) this;
		}

		public Criteria andAppkeyIn(List<String> values) {
			addCriterion("appkey in", values, "appkey");
			return (Criteria) this;
		}

		public Criteria andAppkeyNotIn(List<String> values) {
			addCriterion("appkey not in", values, "appkey");
			return (Criteria) this;
		}

		public Criteria andAppkeyBetween(String value1, String value2) {
			addCriterion("appkey between", value1, value2, "appkey");
			return (Criteria) this;
		}

		public Criteria andAppkeyNotBetween(String value1, String value2) {
			addCriterion("appkey not between", value1, value2, "appkey");
			return (Criteria) this;
		}

		public Criteria andApiIdIsNull() {
			addCriterion("api_id is null");
			return (Criteria) this;
		}

		public Criteria andApiIdIsNotNull() {
			addCriterion("api_id is not null");
			return (Criteria) this;
		}

		public Criteria andApiIdEqualTo(Integer value) {
			addCriterion("api_id =", value, "apiId");
			return (Criteria) this;
		}

		public Criteria andApiIdNotEqualTo(Integer value) {
			addCriterion("api_id <>", value, "apiId");
			return (Criteria) this;
		}

		public Criteria andApiIdGreaterThan(Integer value) {
			addCriterion("api_id >", value, "apiId");
			return (Criteria) this;
		}

		public Criteria andApiIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("api_id >=", value, "apiId");
			return (Criteria) this;
		}

		public Criteria andApiIdLessThan(Integer value) {
			addCriterion("api_id <", value, "apiId");
			return (Criteria) this;
		}

		public Criteria andApiIdLessThanOrEqualTo(Integer value) {
			addCriterion("api_id <=", value, "apiId");
			return (Criteria) this;
		}

		public Criteria andApiIdIn(List<Integer> values) {
			addCriterion("api_id in", values, "apiId");
			return (Criteria) this;
		}

		public Criteria andApiIdNotIn(List<Integer> values) {
			addCriterion("api_id not in", values, "apiId");
			return (Criteria) this;
		}

		public Criteria andApiIdBetween(Integer value1, Integer value2) {
			addCriterion("api_id between", value1, value2, "apiId");
			return (Criteria) this;
		}

		public Criteria andApiIdNotBetween(Integer value1, Integer value2) {
			addCriterion("api_id not between", value1, value2, "apiId");
			return (Criteria) this;
		}

		public Criteria andApiVersionIsNull() {
			addCriterion("api_version is null");
			return (Criteria) this;
		}

		public Criteria andApiVersionIsNotNull() {
			addCriterion("api_version is not null");
			return (Criteria) this;
		}

		public Criteria andApiVersionEqualTo(Integer value) {
			addCriterion("api_version =", value, "apiVersion");
			return (Criteria) this;
		}

		public Criteria andApiVersionNotEqualTo(Integer value) {
			addCriterion("api_version <>", value, "apiVersion");
			return (Criteria) this;
		}

		public Criteria andApiVersionGreaterThan(Integer value) {
			addCriterion("api_version >", value, "apiVersion");
			return (Criteria) this;
		}

		public Criteria andApiVersionGreaterThanOrEqualTo(Integer value) {
			addCriterion("api_version >=", value, "apiVersion");
			return (Criteria) this;
		}

		public Criteria andApiVersionLessThan(Integer value) {
			addCriterion("api_version <", value, "apiVersion");
			return (Criteria) this;
		}

		public Criteria andApiVersionLessThanOrEqualTo(Integer value) {
			addCriterion("api_version <=", value, "apiVersion");
			return (Criteria) this;
		}

		public Criteria andApiVersionIn(List<Integer> values) {
			addCriterion("api_version in", values, "apiVersion");
			return (Criteria) this;
		}

		public Criteria andApiVersionNotIn(List<Integer> values) {
			addCriterion("api_version not in", values, "apiVersion");
			return (Criteria) this;
		}

		public Criteria andApiVersionBetween(Integer value1, Integer value2) {
			addCriterion("api_version between", value1, value2, "apiVersion");
			return (Criteria) this;
		}

		public Criteria andApiVersionNotBetween(Integer value1, Integer value2) {
			addCriterion("api_version not between", value1, value2, "apiVersion");
			return (Criteria) this;
		}

		public Criteria andApiNameIsNull() {
			addCriterion("api_name is null");
			return (Criteria) this;
		}

		public Criteria andApiNameIsNotNull() {
			addCriterion("api_name is not null");
			return (Criteria) this;
		}

		public Criteria andApiNameEqualTo(String value) {
			addCriterion("api_name =", value, "apiName");
			return (Criteria) this;
		}

		public Criteria andApiNameNotEqualTo(String value) {
			addCriterion("api_name <>", value, "apiName");
			return (Criteria) this;
		}

		public Criteria andApiNameGreaterThan(String value) {
			addCriterion("api_name >", value, "apiName");
			return (Criteria) this;
		}

		public Criteria andApiNameGreaterThanOrEqualTo(String value) {
			addCriterion("api_name >=", value, "apiName");
			return (Criteria) this;
		}

		public Criteria andApiNameLessThan(String value) {
			addCriterion("api_name <", value, "apiName");
			return (Criteria) this;
		}

		public Criteria andApiNameLessThanOrEqualTo(String value) {
			addCriterion("api_name <=", value, "apiName");
			return (Criteria) this;
		}

		public Criteria andApiNameLike(String value) {
			addCriterion("api_name like", value, "apiName");
			return (Criteria) this;
		}

		public Criteria andApiNameNotLike(String value) {
			addCriterion("api_name not like", value, "apiName");
			return (Criteria) this;
		}

		public Criteria andApiNameIn(List<String> values) {
			addCriterion("api_name in", values, "apiName");
			return (Criteria) this;
		}

		public Criteria andApiNameNotIn(List<String> values) {
			addCriterion("api_name not in", values, "apiName");
			return (Criteria) this;
		}

		public Criteria andApiNameBetween(String value1, String value2) {
			addCriterion("api_name between", value1, value2, "apiName");
			return (Criteria) this;
		}

		public Criteria andApiNameNotBetween(String value1, String value2) {
			addCriterion("api_name not between", value1, value2, "apiName");
			return (Criteria) this;
		}

		public Criteria andApiSortIsNull() {
			addCriterion("api_sort is null");
			return (Criteria) this;
		}

		public Criteria andApiSortIsNotNull() {
			addCriterion("api_sort is not null");
			return (Criteria) this;
		}

		public Criteria andApiSortEqualTo(Integer value) {
			addCriterion("api_sort =", value, "apiSort");
			return (Criteria) this;
		}

		public Criteria andApiSortNotEqualTo(Integer value) {
			addCriterion("api_sort <>", value, "apiSort");
			return (Criteria) this;
		}

		public Criteria andApiSortGreaterThan(Integer value) {
			addCriterion("api_sort >", value, "apiSort");
			return (Criteria) this;
		}

		public Criteria andApiSortGreaterThanOrEqualTo(Integer value) {
			addCriterion("api_sort >=", value, "apiSort");
			return (Criteria) this;
		}

		public Criteria andApiSortLessThan(Integer value) {
			addCriterion("api_sort <", value, "apiSort");
			return (Criteria) this;
		}

		public Criteria andApiSortLessThanOrEqualTo(Integer value) {
			addCriterion("api_sort <=", value, "apiSort");
			return (Criteria) this;
		}

		public Criteria andApiSortIn(List<Integer> values) {
			addCriterion("api_sort in", values, "apiSort");
			return (Criteria) this;
		}

		public Criteria andApiSortNotIn(List<Integer> values) {
			addCriterion("api_sort not in", values, "apiSort");
			return (Criteria) this;
		}

		public Criteria andApiSortBetween(Integer value1, Integer value2) {
			addCriterion("api_sort between", value1, value2, "apiSort");
			return (Criteria) this;
		}

		public Criteria andApiSortNotBetween(Integer value1, Integer value2) {
			addCriterion("api_sort not between", value1, value2, "apiSort");
			return (Criteria) this;
		}

		public Criteria andApiSortNameIsNull() {
			addCriterion("api_sort_name is null");
			return (Criteria) this;
		}

		public Criteria andApiSortNameIsNotNull() {
			addCriterion("api_sort_name is not null");
			return (Criteria) this;
		}

		public Criteria andApiSortNameEqualTo(String value) {
			addCriterion("api_sort_name =", value, "apiSortName");
			return (Criteria) this;
		}

		public Criteria andApiSortNameNotEqualTo(String value) {
			addCriterion("api_sort_name <>", value, "apiSortName");
			return (Criteria) this;
		}

		public Criteria andApiSortNameGreaterThan(String value) {
			addCriterion("api_sort_name >", value, "apiSortName");
			return (Criteria) this;
		}

		public Criteria andApiSortNameGreaterThanOrEqualTo(String value) {
			addCriterion("api_sort_name >=", value, "apiSortName");
			return (Criteria) this;
		}

		public Criteria andApiSortNameLessThan(String value) {
			addCriterion("api_sort_name <", value, "apiSortName");
			return (Criteria) this;
		}

		public Criteria andApiSortNameLessThanOrEqualTo(String value) {
			addCriterion("api_sort_name <=", value, "apiSortName");
			return (Criteria) this;
		}

		public Criteria andApiSortNameLike(String value) {
			addCriterion("api_sort_name like", value, "apiSortName");
			return (Criteria) this;
		}

		public Criteria andApiSortNameNotLike(String value) {
			addCriterion("api_sort_name not like", value, "apiSortName");
			return (Criteria) this;
		}

		public Criteria andApiSortNameIn(List<String> values) {
			addCriterion("api_sort_name in", values, "apiSortName");
			return (Criteria) this;
		}

		public Criteria andApiSortNameNotIn(List<String> values) {
			addCriterion("api_sort_name not in", values, "apiSortName");
			return (Criteria) this;
		}

		public Criteria andApiSortNameBetween(String value1, String value2) {
			addCriterion("api_sort_name between", value1, value2, "apiSortName");
			return (Criteria) this;
		}

		public Criteria andApiSortNameNotBetween(String value1, String value2) {
			addCriterion("api_sort_name not between", value1, value2, "apiSortName");
			return (Criteria) this;
		}

		public Criteria andApiClsCodeIsNull() {
			addCriterion("api_cls_code is null");
			return (Criteria) this;
		}

		public Criteria andApiClsCodeIsNotNull() {
			addCriterion("api_cls_code is not null");
			return (Criteria) this;
		}

		public Criteria andApiClsCodeEqualTo(Integer value) {
			addCriterion("api_cls_code =", value, "apiClsCode");
			return (Criteria) this;
		}

		public Criteria andApiClsCodeNotEqualTo(Integer value) {
			addCriterion("api_cls_code <>", value, "apiClsCode");
			return (Criteria) this;
		}

		public Criteria andApiClsCodeGreaterThan(Integer value) {
			addCriterion("api_cls_code >", value, "apiClsCode");
			return (Criteria) this;
		}

		public Criteria andApiClsCodeGreaterThanOrEqualTo(Integer value) {
			addCriterion("api_cls_code >=", value, "apiClsCode");
			return (Criteria) this;
		}

		public Criteria andApiClsCodeLessThan(Integer value) {
			addCriterion("api_cls_code <", value, "apiClsCode");
			return (Criteria) this;
		}

		public Criteria andApiClsCodeLessThanOrEqualTo(Integer value) {
			addCriterion("api_cls_code <=", value, "apiClsCode");
			return (Criteria) this;
		}

		public Criteria andApiClsCodeIn(List<Integer> values) {
			addCriterion("api_cls_code in", values, "apiClsCode");
			return (Criteria) this;
		}

		public Criteria andApiClsCodeNotIn(List<Integer> values) {
			addCriterion("api_cls_code not in", values, "apiClsCode");
			return (Criteria) this;
		}

		public Criteria andApiClsCodeBetween(Integer value1, Integer value2) {
			addCriterion("api_cls_code between", value1, value2, "apiClsCode");
			return (Criteria) this;
		}

		public Criteria andApiClsCodeNotBetween(Integer value1, Integer value2) {
			addCriterion("api_cls_code not between", value1, value2, "apiClsCode");
			return (Criteria) this;
		}

		public Criteria andApiClsDescIsNull() {
			addCriterion("api_cls_desc is null");
			return (Criteria) this;
		}

		public Criteria andApiClsDescIsNotNull() {
			addCriterion("api_cls_desc is not null");
			return (Criteria) this;
		}

		public Criteria andApiClsDescEqualTo(String value) {
			addCriterion("api_cls_desc =", value, "apiClsDesc");
			return (Criteria) this;
		}

		public Criteria andApiClsDescNotEqualTo(String value) {
			addCriterion("api_cls_desc <>", value, "apiClsDesc");
			return (Criteria) this;
		}

		public Criteria andApiClsDescGreaterThan(String value) {
			addCriterion("api_cls_desc >", value, "apiClsDesc");
			return (Criteria) this;
		}

		public Criteria andApiClsDescGreaterThanOrEqualTo(String value) {
			addCriterion("api_cls_desc >=", value, "apiClsDesc");
			return (Criteria) this;
		}

		public Criteria andApiClsDescLessThan(String value) {
			addCriterion("api_cls_desc <", value, "apiClsDesc");
			return (Criteria) this;
		}

		public Criteria andApiClsDescLessThanOrEqualTo(String value) {
			addCriterion("api_cls_desc <=", value, "apiClsDesc");
			return (Criteria) this;
		}

		public Criteria andApiClsDescLike(String value) {
			addCriterion("api_cls_desc like", value, "apiClsDesc");
			return (Criteria) this;
		}

		public Criteria andApiClsDescNotLike(String value) {
			addCriterion("api_cls_desc not like", value, "apiClsDesc");
			return (Criteria) this;
		}

		public Criteria andApiClsDescIn(List<String> values) {
			addCriterion("api_cls_desc in", values, "apiClsDesc");
			return (Criteria) this;
		}

		public Criteria andApiClsDescNotIn(List<String> values) {
			addCriterion("api_cls_desc not in", values, "apiClsDesc");
			return (Criteria) this;
		}

		public Criteria andApiClsDescBetween(String value1, String value2) {
			addCriterion("api_cls_desc between", value1, value2, "apiClsDesc");
			return (Criteria) this;
		}

		public Criteria andApiClsDescNotBetween(String value1, String value2) {
			addCriterion("api_cls_desc not between", value1, value2, "apiClsDesc");
			return (Criteria) this;
		}

		public Criteria andDataCycleTypeIsNull() {
			addCriterion("data_cycle_type is null");
			return (Criteria) this;
		}

		public Criteria andDataCycleTypeIsNotNull() {
			addCriterion("data_cycle_type is not null");
			return (Criteria) this;
		}

		public Criteria andDataCycleTypeEqualTo(Integer value) {
			addCriterion("data_cycle_type =", value, "dataCycleType");
			return (Criteria) this;
		}

		public Criteria andDataCycleTypeNotEqualTo(Integer value) {
			addCriterion("data_cycle_type <>", value, "dataCycleType");
			return (Criteria) this;
		}

		public Criteria andDataCycleTypeGreaterThan(Integer value) {
			addCriterion("data_cycle_type >", value, "dataCycleType");
			return (Criteria) this;
		}

		public Criteria andDataCycleTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("data_cycle_type >=", value, "dataCycleType");
			return (Criteria) this;
		}

		public Criteria andDataCycleTypeLessThan(Integer value) {
			addCriterion("data_cycle_type <", value, "dataCycleType");
			return (Criteria) this;
		}

		public Criteria andDataCycleTypeLessThanOrEqualTo(Integer value) {
			addCriterion("data_cycle_type <=", value, "dataCycleType");
			return (Criteria) this;
		}

		public Criteria andDataCycleTypeIn(List<Integer> values) {
			addCriterion("data_cycle_type in", values, "dataCycleType");
			return (Criteria) this;
		}

		public Criteria andDataCycleTypeNotIn(List<Integer> values) {
			addCriterion("data_cycle_type not in", values, "dataCycleType");
			return (Criteria) this;
		}

		public Criteria andDataCycleTypeBetween(Integer value1, Integer value2) {
			addCriterion("data_cycle_type between", value1, value2, "dataCycleType");
			return (Criteria) this;
		}

		public Criteria andDataCycleTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("data_cycle_type not between", value1, value2, "dataCycleType");
			return (Criteria) this;
		}

		public Criteria andDataCycleDescIsNull() {
			addCriterion("data_cycle_desc is null");
			return (Criteria) this;
		}

		public Criteria andDataCycleDescIsNotNull() {
			addCriterion("data_cycle_desc is not null");
			return (Criteria) this;
		}

		public Criteria andDataCycleDescEqualTo(String value) {
			addCriterion("data_cycle_desc =", value, "dataCycleDesc");
			return (Criteria) this;
		}

		public Criteria andDataCycleDescNotEqualTo(String value) {
			addCriterion("data_cycle_desc <>", value, "dataCycleDesc");
			return (Criteria) this;
		}

		public Criteria andDataCycleDescGreaterThan(String value) {
			addCriterion("data_cycle_desc >", value, "dataCycleDesc");
			return (Criteria) this;
		}

		public Criteria andDataCycleDescGreaterThanOrEqualTo(String value) {
			addCriterion("data_cycle_desc >=", value, "dataCycleDesc");
			return (Criteria) this;
		}

		public Criteria andDataCycleDescLessThan(String value) {
			addCriterion("data_cycle_desc <", value, "dataCycleDesc");
			return (Criteria) this;
		}

		public Criteria andDataCycleDescLessThanOrEqualTo(String value) {
			addCriterion("data_cycle_desc <=", value, "dataCycleDesc");
			return (Criteria) this;
		}

		public Criteria andDataCycleDescLike(String value) {
			addCriterion("data_cycle_desc like", value, "dataCycleDesc");
			return (Criteria) this;
		}

		public Criteria andDataCycleDescNotLike(String value) {
			addCriterion("data_cycle_desc not like", value, "dataCycleDesc");
			return (Criteria) this;
		}

		public Criteria andDataCycleDescIn(List<String> values) {
			addCriterion("data_cycle_desc in", values, "dataCycleDesc");
			return (Criteria) this;
		}

		public Criteria andDataCycleDescNotIn(List<String> values) {
			addCriterion("data_cycle_desc not in", values, "dataCycleDesc");
			return (Criteria) this;
		}

		public Criteria andDataCycleDescBetween(String value1, String value2) {
			addCriterion("data_cycle_desc between", value1, value2, "dataCycleDesc");
			return (Criteria) this;
		}

		public Criteria andDataCycleDescNotBetween(String value1, String value2) {
			addCriterion("data_cycle_desc not between", value1, value2, "dataCycleDesc");
			return (Criteria) this;
		}

		public Criteria andFormCodeIsNull() {
			addCriterion("form_code is null");
			return (Criteria) this;
		}

		public Criteria andFormCodeIsNotNull() {
			addCriterion("form_code is not null");
			return (Criteria) this;
		}

		public Criteria andFormCodeEqualTo(String value) {
			addCriterion("form_code =", value, "formCode");
			return (Criteria) this;
		}

		public Criteria andFormCodeNotEqualTo(String value) {
			addCriterion("form_code <>", value, "formCode");
			return (Criteria) this;
		}

		public Criteria andFormCodeGreaterThan(String value) {
			addCriterion("form_code >", value, "formCode");
			return (Criteria) this;
		}

		public Criteria andFormCodeGreaterThanOrEqualTo(String value) {
			addCriterion("form_code >=", value, "formCode");
			return (Criteria) this;
		}

		public Criteria andFormCodeLessThan(String value) {
			addCriterion("form_code <", value, "formCode");
			return (Criteria) this;
		}

		public Criteria andFormCodeLessThanOrEqualTo(String value) {
			addCriterion("form_code <=", value, "formCode");
			return (Criteria) this;
		}

		public Criteria andFormCodeLike(String value) {
			addCriterion("form_code like", value, "formCode");
			return (Criteria) this;
		}

		public Criteria andFormCodeNotLike(String value) {
			addCriterion("form_code not like", value, "formCode");
			return (Criteria) this;
		}

		public Criteria andFormCodeIn(List<String> values) {
			addCriterion("form_code in", values, "formCode");
			return (Criteria) this;
		}

		public Criteria andFormCodeNotIn(List<String> values) {
			addCriterion("form_code not in", values, "formCode");
			return (Criteria) this;
		}

		public Criteria andFormCodeBetween(String value1, String value2) {
			addCriterion("form_code between", value1, value2, "formCode");
			return (Criteria) this;
		}

		public Criteria andFormCodeNotBetween(String value1, String value2) {
			addCriterion("form_code not between", value1, value2, "formCode");
			return (Criteria) this;
		}

		public Criteria andEncodeIsNull() {
			addCriterion("encode is null");
			return (Criteria) this;
		}

		public Criteria andEncodeIsNotNull() {
			addCriterion("encode is not null");
			return (Criteria) this;
		}

		public Criteria andEncodeEqualTo(String value) {
			addCriterion("encode =", value, "encode");
			return (Criteria) this;
		}

		public Criteria andEncodeNotEqualTo(String value) {
			addCriterion("encode <>", value, "encode");
			return (Criteria) this;
		}

		public Criteria andEncodeGreaterThan(String value) {
			addCriterion("encode >", value, "encode");
			return (Criteria) this;
		}

		public Criteria andEncodeGreaterThanOrEqualTo(String value) {
			addCriterion("encode >=", value, "encode");
			return (Criteria) this;
		}

		public Criteria andEncodeLessThan(String value) {
			addCriterion("encode <", value, "encode");
			return (Criteria) this;
		}

		public Criteria andEncodeLessThanOrEqualTo(String value) {
			addCriterion("encode <=", value, "encode");
			return (Criteria) this;
		}

		public Criteria andEncodeLike(String value) {
			addCriterion("encode like", value, "encode");
			return (Criteria) this;
		}

		public Criteria andEncodeNotLike(String value) {
			addCriterion("encode not like", value, "encode");
			return (Criteria) this;
		}

		public Criteria andEncodeIn(List<String> values) {
			addCriterion("encode in", values, "encode");
			return (Criteria) this;
		}

		public Criteria andEncodeNotIn(List<String> values) {
			addCriterion("encode not in", values, "encode");
			return (Criteria) this;
		}

		public Criteria andEncodeBetween(String value1, String value2) {
			addCriterion("encode between", value1, value2, "encode");
			return (Criteria) this;
		}

		public Criteria andEncodeNotBetween(String value1, String value2) {
			addCriterion("encode not between", value1, value2, "encode");
			return (Criteria) this;
		}

		public Criteria andReqArgIsNull() {
			addCriterion("req_arg is null");
			return (Criteria) this;
		}

		public Criteria andReqArgIsNotNull() {
			addCriterion("req_arg is not null");
			return (Criteria) this;
		}

		public Criteria andReqArgEqualTo(String value) {
			addCriterion("req_arg =", value, "reqArg");
			return (Criteria) this;
		}

		public Criteria andReqArgNotEqualTo(String value) {
			addCriterion("req_arg <>", value, "reqArg");
			return (Criteria) this;
		}

		public Criteria andReqArgGreaterThan(String value) {
			addCriterion("req_arg >", value, "reqArg");
			return (Criteria) this;
		}

		public Criteria andReqArgGreaterThanOrEqualTo(String value) {
			addCriterion("req_arg >=", value, "reqArg");
			return (Criteria) this;
		}

		public Criteria andReqArgLessThan(String value) {
			addCriterion("req_arg <", value, "reqArg");
			return (Criteria) this;
		}

		public Criteria andReqArgLessThanOrEqualTo(String value) {
			addCriterion("req_arg <=", value, "reqArg");
			return (Criteria) this;
		}

		public Criteria andReqArgLike(String value) {
			addCriterion("req_arg like", value, "reqArg");
			return (Criteria) this;
		}

		public Criteria andReqArgNotLike(String value) {
			addCriterion("req_arg not like", value, "reqArg");
			return (Criteria) this;
		}

		public Criteria andReqArgIn(List<String> values) {
			addCriterion("req_arg in", values, "reqArg");
			return (Criteria) this;
		}

		public Criteria andReqArgNotIn(List<String> values) {
			addCriterion("req_arg not in", values, "reqArg");
			return (Criteria) this;
		}

		public Criteria andReqArgBetween(String value1, String value2) {
			addCriterion("req_arg between", value1, value2, "reqArg");
			return (Criteria) this;
		}

		public Criteria andReqArgNotBetween(String value1, String value2) {
			addCriterion("req_arg not between", value1, value2, "reqArg");
			return (Criteria) this;
		}

		public Criteria andReqArgRenderIsNull() {
			addCriterion("req_arg_render is null");
			return (Criteria) this;
		}

		public Criteria andReqArgRenderIsNotNull() {
			addCriterion("req_arg_render is not null");
			return (Criteria) this;
		}

		public Criteria andReqArgRenderEqualTo(String value) {
			addCriterion("req_arg_render =", value, "reqArgRender");
			return (Criteria) this;
		}

		public Criteria andReqArgRenderNotEqualTo(String value) {
			addCriterion("req_arg_render <>", value, "reqArgRender");
			return (Criteria) this;
		}

		public Criteria andReqArgRenderGreaterThan(String value) {
			addCriterion("req_arg_render >", value, "reqArgRender");
			return (Criteria) this;
		}

		public Criteria andReqArgRenderGreaterThanOrEqualTo(String value) {
			addCriterion("req_arg_render >=", value, "reqArgRender");
			return (Criteria) this;
		}

		public Criteria andReqArgRenderLessThan(String value) {
			addCriterion("req_arg_render <", value, "reqArgRender");
			return (Criteria) this;
		}

		public Criteria andReqArgRenderLessThanOrEqualTo(String value) {
			addCriterion("req_arg_render <=", value, "reqArgRender");
			return (Criteria) this;
		}

		public Criteria andReqArgRenderLike(String value) {
			addCriterion("req_arg_render like", value, "reqArgRender");
			return (Criteria) this;
		}

		public Criteria andReqArgRenderNotLike(String value) {
			addCriterion("req_arg_render not like", value, "reqArgRender");
			return (Criteria) this;
		}

		public Criteria andReqArgRenderIn(List<String> values) {
			addCriterion("req_arg_render in", values, "reqArgRender");
			return (Criteria) this;
		}

		public Criteria andReqArgRenderNotIn(List<String> values) {
			addCriterion("req_arg_render not in", values, "reqArgRender");
			return (Criteria) this;
		}

		public Criteria andReqArgRenderBetween(String value1, String value2) {
			addCriterion("req_arg_render between", value1, value2, "reqArgRender");
			return (Criteria) this;
		}

		public Criteria andReqArgRenderNotBetween(String value1, String value2) {
			addCriterion("req_arg_render not between", value1, value2, "reqArgRender");
			return (Criteria) this;
		}

		public Criteria andRespnArgIsNull() {
			addCriterion("respn_arg is null");
			return (Criteria) this;
		}

		public Criteria andRespnArgIsNotNull() {
			addCriterion("respn_arg is not null");
			return (Criteria) this;
		}

		public Criteria andRespnArgEqualTo(String value) {
			addCriterion("respn_arg =", value, "respnArg");
			return (Criteria) this;
		}

		public Criteria andRespnArgNotEqualTo(String value) {
			addCriterion("respn_arg <>", value, "respnArg");
			return (Criteria) this;
		}

		public Criteria andRespnArgGreaterThan(String value) {
			addCriterion("respn_arg >", value, "respnArg");
			return (Criteria) this;
		}

		public Criteria andRespnArgGreaterThanOrEqualTo(String value) {
			addCriterion("respn_arg >=", value, "respnArg");
			return (Criteria) this;
		}

		public Criteria andRespnArgLessThan(String value) {
			addCriterion("respn_arg <", value, "respnArg");
			return (Criteria) this;
		}

		public Criteria andRespnArgLessThanOrEqualTo(String value) {
			addCriterion("respn_arg <=", value, "respnArg");
			return (Criteria) this;
		}

		public Criteria andRespnArgLike(String value) {
			addCriterion("respn_arg like", value, "respnArg");
			return (Criteria) this;
		}

		public Criteria andRespnArgNotLike(String value) {
			addCriterion("respn_arg not like", value, "respnArg");
			return (Criteria) this;
		}

		public Criteria andRespnArgIn(List<String> values) {
			addCriterion("respn_arg in", values, "respnArg");
			return (Criteria) this;
		}

		public Criteria andRespnArgNotIn(List<String> values) {
			addCriterion("respn_arg not in", values, "respnArg");
			return (Criteria) this;
		}

		public Criteria andRespnArgBetween(String value1, String value2) {
			addCriterion("respn_arg between", value1, value2, "respnArg");
			return (Criteria) this;
		}

		public Criteria andRespnArgNotBetween(String value1, String value2) {
			addCriterion("respn_arg not between", value1, value2, "respnArg");
			return (Criteria) this;
		}

		public Criteria andRespnArgRenderIsNull() {
			addCriterion("respn_arg_render is null");
			return (Criteria) this;
		}

		public Criteria andRespnArgRenderIsNotNull() {
			addCriterion("respn_arg_render is not null");
			return (Criteria) this;
		}

		public Criteria andRespnArgRenderEqualTo(String value) {
			addCriterion("respn_arg_render =", value, "respnArgRender");
			return (Criteria) this;
		}

		public Criteria andRespnArgRenderNotEqualTo(String value) {
			addCriterion("respn_arg_render <>", value, "respnArgRender");
			return (Criteria) this;
		}

		public Criteria andRespnArgRenderGreaterThan(String value) {
			addCriterion("respn_arg_render >", value, "respnArgRender");
			return (Criteria) this;
		}

		public Criteria andRespnArgRenderGreaterThanOrEqualTo(String value) {
			addCriterion("respn_arg_render >=", value, "respnArgRender");
			return (Criteria) this;
		}

		public Criteria andRespnArgRenderLessThan(String value) {
			addCriterion("respn_arg_render <", value, "respnArgRender");
			return (Criteria) this;
		}

		public Criteria andRespnArgRenderLessThanOrEqualTo(String value) {
			addCriterion("respn_arg_render <=", value, "respnArgRender");
			return (Criteria) this;
		}

		public Criteria andRespnArgRenderLike(String value) {
			addCriterion("respn_arg_render like", value, "respnArgRender");
			return (Criteria) this;
		}

		public Criteria andRespnArgRenderNotLike(String value) {
			addCriterion("respn_arg_render not like", value, "respnArgRender");
			return (Criteria) this;
		}

		public Criteria andRespnArgRenderIn(List<String> values) {
			addCriterion("respn_arg_render in", values, "respnArgRender");
			return (Criteria) this;
		}

		public Criteria andRespnArgRenderNotIn(List<String> values) {
			addCriterion("respn_arg_render not in", values, "respnArgRender");
			return (Criteria) this;
		}

		public Criteria andRespnArgRenderBetween(String value1, String value2) {
			addCriterion("respn_arg_render between", value1, value2, "respnArgRender");
			return (Criteria) this;
		}

		public Criteria andRespnArgRenderNotBetween(String value1, String value2) {
			addCriterion("respn_arg_render not between", value1, value2, "respnArgRender");
			return (Criteria) this;
		}

		public Criteria andPushArgIsNull() {
			addCriterion("push_arg is null");
			return (Criteria) this;
		}

		public Criteria andPushArgIsNotNull() {
			addCriterion("push_arg is not null");
			return (Criteria) this;
		}

		public Criteria andPushArgEqualTo(String value) {
			addCriterion("push_arg =", value, "pushArg");
			return (Criteria) this;
		}

		public Criteria andPushArgNotEqualTo(String value) {
			addCriterion("push_arg <>", value, "pushArg");
			return (Criteria) this;
		}

		public Criteria andPushArgGreaterThan(String value) {
			addCriterion("push_arg >", value, "pushArg");
			return (Criteria) this;
		}

		public Criteria andPushArgGreaterThanOrEqualTo(String value) {
			addCriterion("push_arg >=", value, "pushArg");
			return (Criteria) this;
		}

		public Criteria andPushArgLessThan(String value) {
			addCriterion("push_arg <", value, "pushArg");
			return (Criteria) this;
		}

		public Criteria andPushArgLessThanOrEqualTo(String value) {
			addCriterion("push_arg <=", value, "pushArg");
			return (Criteria) this;
		}

		public Criteria andPushArgLike(String value) {
			addCriterion("push_arg like", value, "pushArg");
			return (Criteria) this;
		}

		public Criteria andPushArgNotLike(String value) {
			addCriterion("push_arg not like", value, "pushArg");
			return (Criteria) this;
		}

		public Criteria andPushArgIn(List<String> values) {
			addCriterion("push_arg in", values, "pushArg");
			return (Criteria) this;
		}

		public Criteria andPushArgNotIn(List<String> values) {
			addCriterion("push_arg not in", values, "pushArg");
			return (Criteria) this;
		}

		public Criteria andPushArgBetween(String value1, String value2) {
			addCriterion("push_arg between", value1, value2, "pushArg");
			return (Criteria) this;
		}

		public Criteria andPushArgNotBetween(String value1, String value2) {
			addCriterion("push_arg not between", value1, value2, "pushArg");
			return (Criteria) this;
		}

		public Criteria andPushArgRenderIsNull() {
			addCriterion("push_arg_render is null");
			return (Criteria) this;
		}

		public Criteria andPushArgRenderIsNotNull() {
			addCriterion("push_arg_render is not null");
			return (Criteria) this;
		}

		public Criteria andPushArgRenderEqualTo(String value) {
			addCriterion("push_arg_render =", value, "pushArgRender");
			return (Criteria) this;
		}

		public Criteria andPushArgRenderNotEqualTo(String value) {
			addCriterion("push_arg_render <>", value, "pushArgRender");
			return (Criteria) this;
		}

		public Criteria andPushArgRenderGreaterThan(String value) {
			addCriterion("push_arg_render >", value, "pushArgRender");
			return (Criteria) this;
		}

		public Criteria andPushArgRenderGreaterThanOrEqualTo(String value) {
			addCriterion("push_arg_render >=", value, "pushArgRender");
			return (Criteria) this;
		}

		public Criteria andPushArgRenderLessThan(String value) {
			addCriterion("push_arg_render <", value, "pushArgRender");
			return (Criteria) this;
		}

		public Criteria andPushArgRenderLessThanOrEqualTo(String value) {
			addCriterion("push_arg_render <=", value, "pushArgRender");
			return (Criteria) this;
		}

		public Criteria andPushArgRenderLike(String value) {
			addCriterion("push_arg_render like", value, "pushArgRender");
			return (Criteria) this;
		}

		public Criteria andPushArgRenderNotLike(String value) {
			addCriterion("push_arg_render not like", value, "pushArgRender");
			return (Criteria) this;
		}

		public Criteria andPushArgRenderIn(List<String> values) {
			addCriterion("push_arg_render in", values, "pushArgRender");
			return (Criteria) this;
		}

		public Criteria andPushArgRenderNotIn(List<String> values) {
			addCriterion("push_arg_render not in", values, "pushArgRender");
			return (Criteria) this;
		}

		public Criteria andPushArgRenderBetween(String value1, String value2) {
			addCriterion("push_arg_render between", value1, value2, "pushArgRender");
			return (Criteria) this;
		}

		public Criteria andPushArgRenderNotBetween(String value1, String value2) {
			addCriterion("push_arg_render not between", value1, value2, "pushArgRender");
			return (Criteria) this;
		}

		public Criteria andRetnFormFingerIsNull() {
			addCriterion("retn_form_finger is null");
			return (Criteria) this;
		}

		public Criteria andRetnFormFingerIsNotNull() {
			addCriterion("retn_form_finger is not null");
			return (Criteria) this;
		}

		public Criteria andRetnFormFingerEqualTo(String value) {
			addCriterion("retn_form_finger =", value, "retnFormFinger");
			return (Criteria) this;
		}

		public Criteria andRetnFormFingerNotEqualTo(String value) {
			addCriterion("retn_form_finger <>", value, "retnFormFinger");
			return (Criteria) this;
		}

		public Criteria andRetnFormFingerGreaterThan(String value) {
			addCriterion("retn_form_finger >", value, "retnFormFinger");
			return (Criteria) this;
		}

		public Criteria andRetnFormFingerGreaterThanOrEqualTo(String value) {
			addCriterion("retn_form_finger >=", value, "retnFormFinger");
			return (Criteria) this;
		}

		public Criteria andRetnFormFingerLessThan(String value) {
			addCriterion("retn_form_finger <", value, "retnFormFinger");
			return (Criteria) this;
		}

		public Criteria andRetnFormFingerLessThanOrEqualTo(String value) {
			addCriterion("retn_form_finger <=", value, "retnFormFinger");
			return (Criteria) this;
		}

		public Criteria andRetnFormFingerLike(String value) {
			addCriterion("retn_form_finger like", value, "retnFormFinger");
			return (Criteria) this;
		}

		public Criteria andRetnFormFingerNotLike(String value) {
			addCriterion("retn_form_finger not like", value, "retnFormFinger");
			return (Criteria) this;
		}

		public Criteria andRetnFormFingerIn(List<String> values) {
			addCriterion("retn_form_finger in", values, "retnFormFinger");
			return (Criteria) this;
		}

		public Criteria andRetnFormFingerNotIn(List<String> values) {
			addCriterion("retn_form_finger not in", values, "retnFormFinger");
			return (Criteria) this;
		}

		public Criteria andRetnFormFingerBetween(String value1, String value2) {
			addCriterion("retn_form_finger between", value1, value2, "retnFormFinger");
			return (Criteria) this;
		}

		public Criteria andRetnFormFingerNotBetween(String value1, String value2) {
			addCriterion("retn_form_finger not between", value1, value2, "retnFormFinger");
			return (Criteria) this;
		}

		public Criteria andRetnDataFingerIsNull() {
			addCriterion("retn_data_finger is null");
			return (Criteria) this;
		}

		public Criteria andRetnDataFingerIsNotNull() {
			addCriterion("retn_data_finger is not null");
			return (Criteria) this;
		}

		public Criteria andRetnDataFingerEqualTo(String value) {
			addCriterion("retn_data_finger =", value, "retnDataFinger");
			return (Criteria) this;
		}

		public Criteria andRetnDataFingerNotEqualTo(String value) {
			addCriterion("retn_data_finger <>", value, "retnDataFinger");
			return (Criteria) this;
		}

		public Criteria andRetnDataFingerGreaterThan(String value) {
			addCriterion("retn_data_finger >", value, "retnDataFinger");
			return (Criteria) this;
		}

		public Criteria andRetnDataFingerGreaterThanOrEqualTo(String value) {
			addCriterion("retn_data_finger >=", value, "retnDataFinger");
			return (Criteria) this;
		}

		public Criteria andRetnDataFingerLessThan(String value) {
			addCriterion("retn_data_finger <", value, "retnDataFinger");
			return (Criteria) this;
		}

		public Criteria andRetnDataFingerLessThanOrEqualTo(String value) {
			addCriterion("retn_data_finger <=", value, "retnDataFinger");
			return (Criteria) this;
		}

		public Criteria andRetnDataFingerLike(String value) {
			addCriterion("retn_data_finger like", value, "retnDataFinger");
			return (Criteria) this;
		}

		public Criteria andRetnDataFingerNotLike(String value) {
			addCriterion("retn_data_finger not like", value, "retnDataFinger");
			return (Criteria) this;
		}

		public Criteria andRetnDataFingerIn(List<String> values) {
			addCriterion("retn_data_finger in", values, "retnDataFinger");
			return (Criteria) this;
		}

		public Criteria andRetnDataFingerNotIn(List<String> values) {
			addCriterion("retn_data_finger not in", values, "retnDataFinger");
			return (Criteria) this;
		}

		public Criteria andRetnDataFingerBetween(String value1, String value2) {
			addCriterion("retn_data_finger between", value1, value2, "retnDataFinger");
			return (Criteria) this;
		}

		public Criteria andRetnDataFingerNotBetween(String value1, String value2) {
			addCriterion("retn_data_finger not between", value1, value2, "retnDataFinger");
			return (Criteria) this;
		}

		public Criteria andTriggerMethdIsNull() {
			addCriterion("trigger_methd is null");
			return (Criteria) this;
		}

		public Criteria andTriggerMethdIsNotNull() {
			addCriterion("trigger_methd is not null");
			return (Criteria) this;
		}

		public Criteria andTriggerMethdEqualTo(Integer value) {
			addCriterion("trigger_methd =", value, "triggerMethd");
			return (Criteria) this;
		}

		public Criteria andTriggerMethdNotEqualTo(Integer value) {
			addCriterion("trigger_methd <>", value, "triggerMethd");
			return (Criteria) this;
		}

		public Criteria andTriggerMethdGreaterThan(Integer value) {
			addCriterion("trigger_methd >", value, "triggerMethd");
			return (Criteria) this;
		}

		public Criteria andTriggerMethdGreaterThanOrEqualTo(Integer value) {
			addCriterion("trigger_methd >=", value, "triggerMethd");
			return (Criteria) this;
		}

		public Criteria andTriggerMethdLessThan(Integer value) {
			addCriterion("trigger_methd <", value, "triggerMethd");
			return (Criteria) this;
		}

		public Criteria andTriggerMethdLessThanOrEqualTo(Integer value) {
			addCriterion("trigger_methd <=", value, "triggerMethd");
			return (Criteria) this;
		}

		public Criteria andTriggerMethdIn(List<Integer> values) {
			addCriterion("trigger_methd in", values, "triggerMethd");
			return (Criteria) this;
		}

		public Criteria andTriggerMethdNotIn(List<Integer> values) {
			addCriterion("trigger_methd not in", values, "triggerMethd");
			return (Criteria) this;
		}

		public Criteria andTriggerMethdBetween(Integer value1, Integer value2) {
			addCriterion("trigger_methd between", value1, value2, "triggerMethd");
			return (Criteria) this;
		}

		public Criteria andTriggerMethdNotBetween(Integer value1, Integer value2) {
			addCriterion("trigger_methd not between", value1, value2, "triggerMethd");
			return (Criteria) this;
		}

		public Criteria andTriggerMethdDescIsNull() {
			addCriterion("trigger_methd_desc is null");
			return (Criteria) this;
		}

		public Criteria andTriggerMethdDescIsNotNull() {
			addCriterion("trigger_methd_desc is not null");
			return (Criteria) this;
		}

		public Criteria andTriggerMethdDescEqualTo(String value) {
			addCriterion("trigger_methd_desc =", value, "triggerMethdDesc");
			return (Criteria) this;
		}

		public Criteria andTriggerMethdDescNotEqualTo(String value) {
			addCriterion("trigger_methd_desc <>", value, "triggerMethdDesc");
			return (Criteria) this;
		}

		public Criteria andTriggerMethdDescGreaterThan(String value) {
			addCriterion("trigger_methd_desc >", value, "triggerMethdDesc");
			return (Criteria) this;
		}

		public Criteria andTriggerMethdDescGreaterThanOrEqualTo(String value) {
			addCriterion("trigger_methd_desc >=", value, "triggerMethdDesc");
			return (Criteria) this;
		}

		public Criteria andTriggerMethdDescLessThan(String value) {
			addCriterion("trigger_methd_desc <", value, "triggerMethdDesc");
			return (Criteria) this;
		}

		public Criteria andTriggerMethdDescLessThanOrEqualTo(String value) {
			addCriterion("trigger_methd_desc <=", value, "triggerMethdDesc");
			return (Criteria) this;
		}

		public Criteria andTriggerMethdDescLike(String value) {
			addCriterion("trigger_methd_desc like", value, "triggerMethdDesc");
			return (Criteria) this;
		}

		public Criteria andTriggerMethdDescNotLike(String value) {
			addCriterion("trigger_methd_desc not like", value, "triggerMethdDesc");
			return (Criteria) this;
		}

		public Criteria andTriggerMethdDescIn(List<String> values) {
			addCriterion("trigger_methd_desc in", values, "triggerMethdDesc");
			return (Criteria) this;
		}

		public Criteria andTriggerMethdDescNotIn(List<String> values) {
			addCriterion("trigger_methd_desc not in", values, "triggerMethdDesc");
			return (Criteria) this;
		}

		public Criteria andTriggerMethdDescBetween(String value1, String value2) {
			addCriterion("trigger_methd_desc between", value1, value2, "triggerMethdDesc");
			return (Criteria) this;
		}

		public Criteria andTriggerMethdDescNotBetween(String value1, String value2) {
			addCriterion("trigger_methd_desc not between", value1, value2, "triggerMethdDesc");
			return (Criteria) this;
		}

		public Criteria andTriggerSorcIsNull() {
			addCriterion("trigger_sorc is null");
			return (Criteria) this;
		}

		public Criteria andTriggerSorcIsNotNull() {
			addCriterion("trigger_sorc is not null");
			return (Criteria) this;
		}

		public Criteria andTriggerSorcEqualTo(String value) {
			addCriterion("trigger_sorc =", value, "triggerSorc");
			return (Criteria) this;
		}

		public Criteria andTriggerSorcNotEqualTo(String value) {
			addCriterion("trigger_sorc <>", value, "triggerSorc");
			return (Criteria) this;
		}

		public Criteria andTriggerSorcGreaterThan(String value) {
			addCriterion("trigger_sorc >", value, "triggerSorc");
			return (Criteria) this;
		}

		public Criteria andTriggerSorcGreaterThanOrEqualTo(String value) {
			addCriterion("trigger_sorc >=", value, "triggerSorc");
			return (Criteria) this;
		}

		public Criteria andTriggerSorcLessThan(String value) {
			addCriterion("trigger_sorc <", value, "triggerSorc");
			return (Criteria) this;
		}

		public Criteria andTriggerSorcLessThanOrEqualTo(String value) {
			addCriterion("trigger_sorc <=", value, "triggerSorc");
			return (Criteria) this;
		}

		public Criteria andTriggerSorcLike(String value) {
			addCriterion("trigger_sorc like", value, "triggerSorc");
			return (Criteria) this;
		}

		public Criteria andTriggerSorcNotLike(String value) {
			addCriterion("trigger_sorc not like", value, "triggerSorc");
			return (Criteria) this;
		}

		public Criteria andTriggerSorcIn(List<String> values) {
			addCriterion("trigger_sorc in", values, "triggerSorc");
			return (Criteria) this;
		}

		public Criteria andTriggerSorcNotIn(List<String> values) {
			addCriterion("trigger_sorc not in", values, "triggerSorc");
			return (Criteria) this;
		}

		public Criteria andTriggerSorcBetween(String value1, String value2) {
			addCriterion("trigger_sorc between", value1, value2, "triggerSorc");
			return (Criteria) this;
		}

		public Criteria andTriggerSorcNotBetween(String value1, String value2) {
			addCriterion("trigger_sorc not between", value1, value2, "triggerSorc");
			return (Criteria) this;
		}

		public Criteria andPriorityIsNull() {
			addCriterion("priority is null");
			return (Criteria) this;
		}

		public Criteria andPriorityIsNotNull() {
			addCriterion("priority is not null");
			return (Criteria) this;
		}

		public Criteria andPriorityEqualTo(Integer value) {
			addCriterion("priority =", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityNotEqualTo(Integer value) {
			addCriterion("priority <>", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityGreaterThan(Integer value) {
			addCriterion("priority >", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityGreaterThanOrEqualTo(Integer value) {
			addCriterion("priority >=", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityLessThan(Integer value) {
			addCriterion("priority <", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityLessThanOrEqualTo(Integer value) {
			addCriterion("priority <=", value, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityIn(List<Integer> values) {
			addCriterion("priority in", values, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityNotIn(List<Integer> values) {
			addCriterion("priority not in", values, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityBetween(Integer value1, Integer value2) {
			addCriterion("priority between", value1, value2, "priority");
			return (Criteria) this;
		}

		public Criteria andPriorityNotBetween(Integer value1, Integer value2) {
			addCriterion("priority not between", value1, value2, "priority");
			return (Criteria) this;
		}

		public Criteria andEffFlagIsNull() {
			addCriterion("eff_flag is null");
			return (Criteria) this;
		}

		public Criteria andEffFlagIsNotNull() {
			addCriterion("eff_flag is not null");
			return (Criteria) this;
		}

		public Criteria andEffFlagEqualTo(Integer value) {
			addCriterion("eff_flag =", value, "effFlag");
			return (Criteria) this;
		}

		public Criteria andEffFlagNotEqualTo(Integer value) {
			addCriterion("eff_flag <>", value, "effFlag");
			return (Criteria) this;
		}

		public Criteria andEffFlagGreaterThan(Integer value) {
			addCriterion("eff_flag >", value, "effFlag");
			return (Criteria) this;
		}

		public Criteria andEffFlagGreaterThanOrEqualTo(Integer value) {
			addCriterion("eff_flag >=", value, "effFlag");
			return (Criteria) this;
		}

		public Criteria andEffFlagLessThan(Integer value) {
			addCriterion("eff_flag <", value, "effFlag");
			return (Criteria) this;
		}

		public Criteria andEffFlagLessThanOrEqualTo(Integer value) {
			addCriterion("eff_flag <=", value, "effFlag");
			return (Criteria) this;
		}

		public Criteria andEffFlagIn(List<Integer> values) {
			addCriterion("eff_flag in", values, "effFlag");
			return (Criteria) this;
		}

		public Criteria andEffFlagNotIn(List<Integer> values) {
			addCriterion("eff_flag not in", values, "effFlag");
			return (Criteria) this;
		}

		public Criteria andEffFlagBetween(Integer value1, Integer value2) {
			addCriterion("eff_flag between", value1, value2, "effFlag");
			return (Criteria) this;
		}

		public Criteria andEffFlagNotBetween(Integer value1, Integer value2) {
			addCriterion("eff_flag not between", value1, value2, "effFlag");
			return (Criteria) this;
		}

		public Criteria andEffDescIsNull() {
			addCriterion("eff_desc is null");
			return (Criteria) this;
		}

		public Criteria andEffDescIsNotNull() {
			addCriterion("eff_desc is not null");
			return (Criteria) this;
		}

		public Criteria andEffDescEqualTo(String value) {
			addCriterion("eff_desc =", value, "effDesc");
			return (Criteria) this;
		}

		public Criteria andEffDescNotEqualTo(String value) {
			addCriterion("eff_desc <>", value, "effDesc");
			return (Criteria) this;
		}

		public Criteria andEffDescGreaterThan(String value) {
			addCriterion("eff_desc >", value, "effDesc");
			return (Criteria) this;
		}

		public Criteria andEffDescGreaterThanOrEqualTo(String value) {
			addCriterion("eff_desc >=", value, "effDesc");
			return (Criteria) this;
		}

		public Criteria andEffDescLessThan(String value) {
			addCriterion("eff_desc <", value, "effDesc");
			return (Criteria) this;
		}

		public Criteria andEffDescLessThanOrEqualTo(String value) {
			addCriterion("eff_desc <=", value, "effDesc");
			return (Criteria) this;
		}

		public Criteria andEffDescLike(String value) {
			addCriterion("eff_desc like", value, "effDesc");
			return (Criteria) this;
		}

		public Criteria andEffDescNotLike(String value) {
			addCriterion("eff_desc not like", value, "effDesc");
			return (Criteria) this;
		}

		public Criteria andEffDescIn(List<String> values) {
			addCriterion("eff_desc in", values, "effDesc");
			return (Criteria) this;
		}

		public Criteria andEffDescNotIn(List<String> values) {
			addCriterion("eff_desc not in", values, "effDesc");
			return (Criteria) this;
		}

		public Criteria andEffDescBetween(String value1, String value2) {
			addCriterion("eff_desc between", value1, value2, "effDesc");
			return (Criteria) this;
		}

		public Criteria andEffDescNotBetween(String value1, String value2) {
			addCriterion("eff_desc not between", value1, value2, "effDesc");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table opi.api_rss_info_vw
	 * 
	 * @mbggenerated do_not_delete_during_merge Mon Jul 25 11:08:40 CST 2016
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table opi.api_rss_info_vw
	 * 
	 * @mbggenerated Mon Jul 25 11:08:40 CST 2016
	 */
	public static class Criterion {

		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}