package com.teradata.portal.web.sandbox.pojo;

import java.util.Date;

public class ApiInfoModel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info_vw.api_id
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	private Integer apiId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info_vw.api_version
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	private Integer apiVersion;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info_vw.api_cls_code
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	private Integer apiClsCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info_vw.api_cls_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	private String apiClsDesc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info_vw.api_stat_code
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	private Integer apiStatCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info_vw.api_stat_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	private String apiStatDesc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info_vw.api_sort
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	private Integer apiSort;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info_vw.api_sort_name
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	private String apiSortName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info_vw.data_strct_type_code
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	private Integer dataStrctTypeCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info_vw.data_strct_type_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	private String dataStrctTypeDesc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info_vw.relse_type
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	private Integer relseType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info_vw.relse_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	private String relseDesc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info_vw.api_name
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	private String apiName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info_vw.api_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	private String apiDesc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info_vw.data_cycle_type
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	private Integer dataCycleType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info_vw.data_cycle_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	private String dataCycleDesc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info_vw.relse_persn
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	private String relsePersn;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info_vw.relse_time
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	private Date relseTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info_vw.tab_scale_type
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	private Integer tabScaleType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info_vw.tab_scale_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	private String tabScaleDesc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info_vw.exam_stat
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	private Integer examStat;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info_vw.exam_stat_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	private String examStatDesc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info_vw.api_class_name
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	private String apiClassName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info_vw.trigger_methd
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	private Integer triggerMethd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info_vw.trigger_methd_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	private String triggerMethdDesc;

	private String apiVisitMethd;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info_vw.api_id
	 * 
	 * @return the value of opi.api_info_vw.api_id
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public Integer getApiId() {
		return apiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info_vw.api_id
	 * 
	 * @param apiId the value for opi.api_info_vw.api_id
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public void setApiId(Integer apiId) {
		this.apiId = apiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info_vw.api_version
	 * 
	 * @return the value of opi.api_info_vw.api_version
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public Integer getApiVersion() {
		return apiVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info_vw.api_version
	 * 
	 * @param apiVersion the value for opi.api_info_vw.api_version
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public void setApiVersion(Integer apiVersion) {
		this.apiVersion = apiVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info_vw.api_cls_code
	 * 
	 * @return the value of opi.api_info_vw.api_cls_code
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public Integer getApiClsCode() {
		return apiClsCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info_vw.api_cls_code
	 * 
	 * @param apiClsCode the value for opi.api_info_vw.api_cls_code
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public void setApiClsCode(Integer apiClsCode) {
		this.apiClsCode = apiClsCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info_vw.api_cls_desc
	 * 
	 * @return the value of opi.api_info_vw.api_cls_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public String getApiClsDesc() {
		return apiClsDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info_vw.api_cls_desc
	 * 
	 * @param apiClsDesc the value for opi.api_info_vw.api_cls_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public void setApiClsDesc(String apiClsDesc) {
		this.apiClsDesc = apiClsDesc == null ? null : apiClsDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info_vw.api_stat_code
	 * 
	 * @return the value of opi.api_info_vw.api_stat_code
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public Integer getApiStatCode() {
		return apiStatCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info_vw.api_stat_code
	 * 
	 * @param apiStatCode the value for opi.api_info_vw.api_stat_code
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public void setApiStatCode(Integer apiStatCode) {
		this.apiStatCode = apiStatCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info_vw.api_stat_desc
	 * 
	 * @return the value of opi.api_info_vw.api_stat_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public String getApiStatDesc() {
		return apiStatDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info_vw.api_stat_desc
	 * 
	 * @param apiStatDesc the value for opi.api_info_vw.api_stat_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public void setApiStatDesc(String apiStatDesc) {
		this.apiStatDesc = apiStatDesc == null ? null : apiStatDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info_vw.api_sort
	 * 
	 * @return the value of opi.api_info_vw.api_sort
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public Integer getApiSort() {
		return apiSort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info_vw.api_sort
	 * 
	 * @param apiSort the value for opi.api_info_vw.api_sort
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public void setApiSort(Integer apiSort) {
		this.apiSort = apiSort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info_vw.api_sort_name
	 * 
	 * @return the value of opi.api_info_vw.api_sort_name
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public String getApiSortName() {
		return apiSortName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info_vw.api_sort_name
	 * 
	 * @param apiSortName the value for opi.api_info_vw.api_sort_name
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public void setApiSortName(String apiSortName) {
		this.apiSortName = apiSortName == null ? null : apiSortName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * opi.api_info_vw.data_strct_type_code
	 * 
	 * @return the value of opi.api_info_vw.data_strct_type_code
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public Integer getDataStrctTypeCode() {
		return dataStrctTypeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * opi.api_info_vw.data_strct_type_code
	 * 
	 * @param dataStrctTypeCode the value for opi.api_info_vw.data_strct_type_code
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public void setDataStrctTypeCode(Integer dataStrctTypeCode) {
		this.dataStrctTypeCode = dataStrctTypeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * opi.api_info_vw.data_strct_type_desc
	 * 
	 * @return the value of opi.api_info_vw.data_strct_type_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public String getDataStrctTypeDesc() {
		return dataStrctTypeDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * opi.api_info_vw.data_strct_type_desc
	 * 
	 * @param dataStrctTypeDesc the value for opi.api_info_vw.data_strct_type_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public void setDataStrctTypeDesc(String dataStrctTypeDesc) {
		this.dataStrctTypeDesc = dataStrctTypeDesc == null ? null : dataStrctTypeDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info_vw.relse_type
	 * 
	 * @return the value of opi.api_info_vw.relse_type
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public Integer getRelseType() {
		return relseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info_vw.relse_type
	 * 
	 * @param relseType the value for opi.api_info_vw.relse_type
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public void setRelseType(Integer relseType) {
		this.relseType = relseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info_vw.relse_desc
	 * 
	 * @return the value of opi.api_info_vw.relse_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public String getRelseDesc() {
		return relseDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info_vw.relse_desc
	 * 
	 * @param relseDesc the value for opi.api_info_vw.relse_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public void setRelseDesc(String relseDesc) {
		this.relseDesc = relseDesc == null ? null : relseDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info_vw.api_name
	 * 
	 * @return the value of opi.api_info_vw.api_name
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public String getApiName() {
		return apiName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info_vw.api_name
	 * 
	 * @param apiName the value for opi.api_info_vw.api_name
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public void setApiName(String apiName) {
		this.apiName = apiName == null ? null : apiName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info_vw.api_desc
	 * 
	 * @return the value of opi.api_info_vw.api_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public String getApiDesc() {
		return apiDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info_vw.api_desc
	 * 
	 * @param apiDesc the value for opi.api_info_vw.api_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public void setApiDesc(String apiDesc) {
		this.apiDesc = apiDesc == null ? null : apiDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info_vw.data_cycle_type
	 * 
	 * @return the value of opi.api_info_vw.data_cycle_type
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public Integer getDataCycleType() {
		return dataCycleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info_vw.data_cycle_type
	 * 
	 * @param dataCycleType the value for opi.api_info_vw.data_cycle_type
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public void setDataCycleType(Integer dataCycleType) {
		this.dataCycleType = dataCycleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info_vw.data_cycle_desc
	 * 
	 * @return the value of opi.api_info_vw.data_cycle_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public String getDataCycleDesc() {
		return dataCycleDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info_vw.data_cycle_desc
	 * 
	 * @param dataCycleDesc the value for opi.api_info_vw.data_cycle_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public void setDataCycleDesc(String dataCycleDesc) {
		this.dataCycleDesc = dataCycleDesc == null ? null : dataCycleDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info_vw.relse_persn
	 * 
	 * @return the value of opi.api_info_vw.relse_persn
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public String getRelsePersn() {
		return relsePersn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info_vw.relse_persn
	 * 
	 * @param relsePersn the value for opi.api_info_vw.relse_persn
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public void setRelsePersn(String relsePersn) {
		this.relsePersn = relsePersn == null ? null : relsePersn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info_vw.relse_time
	 * 
	 * @return the value of opi.api_info_vw.relse_time
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public Date getRelseTime() {
		return relseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info_vw.relse_time
	 * 
	 * @param relseTime the value for opi.api_info_vw.relse_time
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public void setRelseTime(Date relseTime) {
		this.relseTime = relseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info_vw.tab_scale_type
	 * 
	 * @return the value of opi.api_info_vw.tab_scale_type
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public Integer getTabScaleType() {
		return tabScaleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info_vw.tab_scale_type
	 * 
	 * @param tabScaleType the value for opi.api_info_vw.tab_scale_type
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public void setTabScaleType(Integer tabScaleType) {
		this.tabScaleType = tabScaleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info_vw.tab_scale_desc
	 * 
	 * @return the value of opi.api_info_vw.tab_scale_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public String getTabScaleDesc() {
		return tabScaleDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info_vw.tab_scale_desc
	 * 
	 * @param tabScaleDesc the value for opi.api_info_vw.tab_scale_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public void setTabScaleDesc(String tabScaleDesc) {
		this.tabScaleDesc = tabScaleDesc == null ? null : tabScaleDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info_vw.exam_stat
	 * 
	 * @return the value of opi.api_info_vw.exam_stat
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public Integer getExamStat() {
		return examStat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info_vw.exam_stat
	 * 
	 * @param examStat the value for opi.api_info_vw.exam_stat
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public void setExamStat(Integer examStat) {
		this.examStat = examStat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info_vw.exam_stat_desc
	 * 
	 * @return the value of opi.api_info_vw.exam_stat_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public String getExamStatDesc() {
		return examStatDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info_vw.exam_stat_desc
	 * 
	 * @param examStatDesc the value for opi.api_info_vw.exam_stat_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public void setExamStatDesc(String examStatDesc) {
		this.examStatDesc = examStatDesc == null ? null : examStatDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info_vw.api_class_name
	 * 
	 * @return the value of opi.api_info_vw.api_class_name
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public String getApiClassName() {
		return apiClassName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info_vw.api_class_name
	 * 
	 * @param apiClassName the value for opi.api_info_vw.api_class_name
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public void setApiClassName(String apiClassName) {
		this.apiClassName = apiClassName == null ? null : apiClassName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info_vw.trigger_methd
	 * 
	 * @return the value of opi.api_info_vw.trigger_methd
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public Integer getTriggerMethd() {
		return triggerMethd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info_vw.trigger_methd
	 * 
	 * @param triggerMethd the value for opi.api_info_vw.trigger_methd
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public void setTriggerMethd(Integer triggerMethd) {
		this.triggerMethd = triggerMethd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * opi.api_info_vw.trigger_methd_desc
	 * 
	 * @return the value of opi.api_info_vw.trigger_methd_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public String getTriggerMethdDesc() {
		return triggerMethdDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info_vw.trigger_methd_desc
	 * 
	 * @param triggerMethdDesc the value for opi.api_info_vw.trigger_methd_desc
	 * 
	 * @mbggenerated Fri Jul 29 16:25:34 CST 2016
	 */
	public void setTriggerMethdDesc(String triggerMethdDesc) {
		this.triggerMethdDesc = triggerMethdDesc == null ? null : triggerMethdDesc.trim();
	}

	public String getApiVisitMethd() {
		return apiVisitMethd;
	}

	public void setApiVisitMethd(String apiVisitMethd) {
		this.apiVisitMethd = apiVisitMethd == null ? null : apiVisitMethd.trim();
	}

}