package com.teradata.portal.web.sandbox.pojo;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

public class ApiInfo implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = -9113112427413512893L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info.api_id
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	private Integer apiId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info.api_version
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	private Integer apiVersion;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info.api_cls_code
	 * 
	 * @mbggenerated Wed Jul 13 17:35:25 CST 2016
	 */
	private Integer apiClsCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info.api_stat_code
	 * 
	 * @mbggenerated Wed Jul 13 17:35:25 CST 2016
	 */
	private Integer apiStatCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info.api_sort
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	private Integer apiSort;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info.data_strct_type_code
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	private Integer dataStrctTypeCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info.relse_type
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	private String relseType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info.api_name
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	private String apiName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info.api_desc
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	private String apiDesc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info.data_cycle_type
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	private Integer dataCycleType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info.relse_persn
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	private String relsePersn;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info.relse_time
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	private Date relseTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info.tab_scale_type
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	private Integer tabScaleType;

	private Integer examStat;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_info.api_class_name
	 * 
	 * @mbggenerated Wed Jul 13 16:42:54 CST 2016
	 */
	private String apiClassName;

	private Integer triggerMethod;

	private String apiVisitMethd;

	private List<StructApiArg> apiArgList;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info.api_id
	 * 
	 * @return the value of opi.api_info.api_id
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	public Integer getApiId() {
		return apiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info.api_id
	 * 
	 * @param apiId the value for opi.api_info.api_id
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	public void setApiId(Integer apiId) {
		this.apiId = apiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info.api_version
	 * 
	 * @return the value of opi.api_info.api_version
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	public Integer getApiVersion() {
		return apiVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info.api_version
	 * 
	 * @param apiVersion the value for opi.api_info.api_version
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	public void setApiVersion(Integer apiVersion) {
		this.apiVersion = apiVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info.api_cls_code
	 * 
	 * @return the value of opi.api_info.api_cls_code
	 * 
	 * @mbggenerated Wed Jul 13 11:18:12 CST 2016
	 */
	public Integer getApiClsCode() {
		return apiClsCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info.api_cls_code
	 * 
	 * @param apiClsCode the value for opi.api_info.api_cls_code
	 * 
	 * @mbggenerated Wed Jul 13 11:18:12 CST 2016
	 */
	public void setApiClsCode(Integer apiClsCode) {
		this.apiClsCode = apiClsCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info.api_stat_code
	 * 
	 * @return the value of opi.api_info.api_stat_code
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	public Integer getApiStatCode() {
		return apiStatCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info.api_stat_code
	 * 
	 * @param apiStatCode the value for opi.api_info.api_stat_code
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	public void setApiStatCode(Integer apiStatCode) {
		this.apiStatCode = apiStatCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info.api_sort
	 * 
	 * @return the value of opi.api_info.api_sort
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	public Integer getApiSort() {
		return apiSort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info.api_sort
	 * 
	 * @param apiSort the value for opi.api_info.api_sort
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	public void setApiSort(Integer apiSort) {
		this.apiSort = apiSort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * opi.api_info.data_strct_type_code
	 * 
	 * @return the value of opi.api_info.data_strct_type_code
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	public Integer getDataStrctTypeCode() {
		return dataStrctTypeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info.data_strct_type_code
	 * 
	 * @param dataStrctTypeCode the value for opi.api_info.data_strct_type_code
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	public void setDataStrctTypeCode(Integer dataStrctTypeCode) {
		this.dataStrctTypeCode = dataStrctTypeCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info.relse_type
	 * 
	 * @return the value of opi.api_info.relse_type
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	public String getRelseType() {
		return relseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info.relse_type
	 * 
	 * @param relseType the value for opi.api_info.relse_type
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	public void setRelseType(String relseType) {
		this.relseType = relseType == null ? null : relseType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info.api_name
	 * 
	 * @return the value of opi.api_info.api_name
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	public String getApiName() {
		return apiName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info.api_name
	 * 
	 * @param apiName the value for opi.api_info.api_name
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	public void setApiName(String apiName) {
		this.apiName = apiName == null ? null : apiName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info.api_desc
	 * 
	 * @return the value of opi.api_info.api_desc
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	public String getApiDesc() {
		return apiDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info.api_desc
	 * 
	 * @param apiDesc the value for opi.api_info.api_desc
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	public void setApiDesc(String apiDesc) {
		this.apiDesc = apiDesc == null ? null : apiDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info.data_cycle_type
	 * 
	 * @return the value of opi.api_info.data_cycle_type
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	public Integer getDataCycleType() {
		return dataCycleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info.data_cycle_type
	 * 
	 * @param dataCycleType the value for opi.api_info.data_cycle_type
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	public void setDataCycleType(Integer dataCycleType) {
		this.dataCycleType = dataCycleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info.relse_persn
	 * 
	 * @return the value of opi.api_info.relse_persn
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	public String getRelsePersn() {
		return relsePersn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info.relse_persn
	 * 
	 * @param relsePersn the value for opi.api_info.relse_persn
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	public void setRelsePersn(String relsePersn) {
		this.relsePersn = relsePersn == null ? null : relsePersn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info.relse_time
	 * 
	 * @return the value of opi.api_info.relse_time
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	public Date getRelseTime() {
		return relseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info.relse_time
	 * 
	 * @param relseTime the value for opi.api_info.relse_time
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	public void setRelseTime(Date relseTime) {
		this.relseTime = relseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info.tab_scale_type
	 * 
	 * @return the value of opi.api_info.tab_scale_type
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	public Integer getTabScaleType() {
		return tabScaleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info.tab_scale_type
	 * 
	 * @param tabScaleType the value for opi.api_info.tab_scale_type
	 * 
	 * @mbggenerated Thu May 19 10:52:37 CST 2016
	 */
	public void setTabScaleType(Integer tabScaleType) {
		this.tabScaleType = tabScaleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_info.api_class_name
	 * 
	 * @return the value of opi.api_info.api_class_name
	 * 
	 * @mbggenerated Wed Jul 13 16:42:54 CST 2016
	 */
	public String getApiClassName() {
		return apiClassName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_info.api_class_name
	 * 
	 * @param apiClassName the value for opi.api_info.api_class_name
	 * 
	 * @mbggenerated Wed Jul 13 16:42:54 CST 2016
	 */
	public void setApiClassName(String apiClassName) {
		this.apiClassName = apiClassName == null ? null : apiClassName.trim();
	}

	public Integer getExamStat() {
		return examStat;
	}

	public void setExamStat(Integer examStat) {
		this.examStat = examStat;
	}

	public Integer getTriggerMethod() {
		return triggerMethod;
	}

	public void setTriggerMethod(Integer triggerMethod) {
		this.triggerMethod = triggerMethod;
	}

	public String getApiVisitMethd() {
		return apiVisitMethd;
	}

	public void setApiVisitMethd(String apiVisitMethd) {
		this.apiVisitMethd = apiVisitMethd == null ? null : apiVisitMethd.trim();
	}

	public List<StructApiArg> getApiArgList() {
		return apiArgList;
	}

	public void setApiArgList(List<StructApiArg> apiArgList) {
		this.apiArgList = apiArgList;
	}

}