package com.teradata.portal.web.sandbox.pojo;

public class ApiSortCode {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_sort_code.api_sort
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	private Integer apiSort;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_sort_code.api_sort_name
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	private String apiSortName;

	private String apiSortDesc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_sort_code.api_sort_lvl
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	private Integer apiSortLvl;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.api_sort_code.api_sort_fathr_id
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	private Integer apiSortFathrId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_sort_code.api_sort
	 * 
	 * @return the value of opi.api_sort_code.api_sort
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public Integer getApiSort() {
		return apiSort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_sort_code.api_sort
	 * 
	 * @param apiSort the value for opi.api_sort_code.api_sort
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public void setApiSort(Integer apiSort) {
		this.apiSort = apiSort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_sort_code.api_sort_name
	 * 
	 * @return the value of opi.api_sort_code.api_sort_name
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public String getApiSortName() {
		return apiSortName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_sort_code.api_sort_name
	 * 
	 * @param apiSortName the value for opi.api_sort_code.api_sort_name
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public void setApiSortName(String apiSortName) {
		this.apiSortName = apiSortName == null ? null : apiSortName.trim();
	}

	public String getApiSortDesc() {
		return apiSortDesc;
	}

	public void setApiSortDesc(String apiSortDesc) {
		this.apiSortDesc = apiSortDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.api_sort_code.api_sort_lvl
	 * 
	 * @return the value of opi.api_sort_code.api_sort_lvl
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public Integer getApiSortLvl() {
		return apiSortLvl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_sort_code.api_sort_lvl
	 * 
	 * @param apiSortLvl the value for opi.api_sort_code.api_sort_lvl
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public void setApiSortLvl(Integer apiSortLvl) {
		this.apiSortLvl = apiSortLvl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * opi.api_sort_code.api_sort_fathr_id
	 * 
	 * @return the value of opi.api_sort_code.api_sort_fathr_id
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public Integer getApiSortFathrId() {
		return apiSortFathrId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.api_sort_code.api_sort_fathr_id
	 * 
	 * @param apiSortFathrId the value for opi.api_sort_code.api_sort_fathr_id
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public void setApiSortFathrId(Integer apiSortFathrId) {
		this.apiSortFathrId = apiSortFathrId;
	}
}