package com.teradata.portal.web.sandbox.pojo;

import java.util.Date;

public class ApiTestBox {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opi.api_test_box.box_id
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    private Integer boxId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opi.api_test_box.api_id
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    private Integer apiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opi.api_test_box.api_name
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    private String apiName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opi.api_test_box.app_key
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    private String appKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opi.api_test_box.req_type
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    private String reqType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opi.api_test_box.submit_type
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    private String submitType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opi.api_test_box.return_type
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    private String returnType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opi.api_test_box.req_args
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    private String reqArgs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opi.api_test_box.start_time
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opi.api_test_box.login_name
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opi.api_test_box.test_result
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    private String testResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opi.api_test_box.is_success
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    private String isSuccess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column opi.api_test_box.api_version
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    private Integer apiVersion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opi.api_test_box.box_id
     *
     * @return the value of opi.api_test_box.box_id
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    public Integer getBoxId() {
        return boxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opi.api_test_box.box_id
     *
     * @param boxId the value for opi.api_test_box.box_id
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    public void setBoxId(Integer boxId) {
        this.boxId = boxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opi.api_test_box.api_id
     *
     * @return the value of opi.api_test_box.api_id
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    public Integer getApiId() {
        return apiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opi.api_test_box.api_id
     *
     * @param apiId the value for opi.api_test_box.api_id
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    public void setApiId(Integer apiId) {
        this.apiId = apiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opi.api_test_box.api_name
     *
     * @return the value of opi.api_test_box.api_name
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    public String getApiName() {
        return apiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opi.api_test_box.api_name
     *
     * @param apiName the value for opi.api_test_box.api_name
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    public void setApiName(String apiName) {
        this.apiName = apiName == null ? null : apiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opi.api_test_box.app_key
     *
     * @return the value of opi.api_test_box.app_key
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opi.api_test_box.app_key
     *
     * @param appKey the value for opi.api_test_box.app_key
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey == null ? null : appKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opi.api_test_box.req_type
     *
     * @return the value of opi.api_test_box.req_type
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    public String getReqType() {
        return reqType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opi.api_test_box.req_type
     *
     * @param reqType the value for opi.api_test_box.req_type
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    public void setReqType(String reqType) {
        this.reqType = reqType == null ? null : reqType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opi.api_test_box.submit_type
     *
     * @return the value of opi.api_test_box.submit_type
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    public String getSubmitType() {
        return submitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opi.api_test_box.submit_type
     *
     * @param submitType the value for opi.api_test_box.submit_type
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    public void setSubmitType(String submitType) {
        this.submitType = submitType == null ? null : submitType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opi.api_test_box.return_type
     *
     * @return the value of opi.api_test_box.return_type
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    public String getReturnType() {
        return returnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opi.api_test_box.return_type
     *
     * @param returnType the value for opi.api_test_box.return_type
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    public void setReturnType(String returnType) {
        this.returnType = returnType == null ? null : returnType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opi.api_test_box.req_args
     *
     * @return the value of opi.api_test_box.req_args
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    public String getReqArgs() {
        return reqArgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opi.api_test_box.req_args
     *
     * @param reqArgs the value for opi.api_test_box.req_args
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    public void setReqArgs(String reqArgs) {
        this.reqArgs = reqArgs == null ? null : reqArgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opi.api_test_box.start_time
     *
     * @return the value of opi.api_test_box.start_time
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opi.api_test_box.start_time
     *
     * @param startTime the value for opi.api_test_box.start_time
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opi.api_test_box.login_name
     *
     * @return the value of opi.api_test_box.login_name
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opi.api_test_box.login_name
     *
     * @param loginName the value for opi.api_test_box.login_name
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opi.api_test_box.test_result
     *
     * @return the value of opi.api_test_box.test_result
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    public String getTestResult() {
        return testResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opi.api_test_box.test_result
     *
     * @param testResult the value for opi.api_test_box.test_result
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    public void setTestResult(String testResult) {
        this.testResult = testResult == null ? null : testResult.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opi.api_test_box.is_success
     *
     * @return the value of opi.api_test_box.is_success
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    public String getIsSuccess() {
        return isSuccess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opi.api_test_box.is_success
     *
     * @param isSuccess the value for opi.api_test_box.is_success
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    public void setIsSuccess(String isSuccess) {
        this.isSuccess = isSuccess == null ? null : isSuccess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column opi.api_test_box.api_version
     *
     * @return the value of opi.api_test_box.api_version
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    public Integer getApiVersion() {
        return apiVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column opi.api_test_box.api_version
     *
     * @param apiVersion the value for opi.api_test_box.api_version
     *
     * @mbggenerated Tue Jun 28 14:37:01 CST 2016
     */
    public void setApiVersion(Integer apiVersion) {
        this.apiVersion = apiVersion;
    }
}