package com.teradata.portal.web.sandbox.pojo;

import java.io.Serializable;

public class StructApiArg implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 727712894546656560L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.struct_api_arg.api_id
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	private Integer apiId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.struct_api_arg.api_version
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	private Integer apiVersion;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.struct_api_arg.field_alias
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	private String fieldAlias;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.struct_api_arg.field_name
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	private String fieldName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.struct_api_arg.field_eff_stat
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	private Integer fieldEffStat;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.struct_api_arg.field_sorc_type
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	private String fieldSorcType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.struct_api_arg.field_targt_type
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	private String fieldTargtType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.struct_api_arg.field_title
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	private String fieldTitle;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.struct_api_arg.sync_must_type
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	private Integer syncMustType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.struct_api_arg.sync_must_one_grp_id
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	private Integer syncMustOneGrpId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.struct_api_arg.asyn_must_type
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	private Integer asynMustType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.struct_api_arg.asyn_must_one_grp_id
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	private Integer asynMustOneGrpId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.struct_api_arg.rss_must_type
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	private Integer rssMustType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.struct_api_arg.rss_must_one_grp_id
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	private Integer rssMustOneGrpId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.struct_api_arg.req_arg_id
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	private String reqArgId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.struct_api_arg.req_arg_deflt_val
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	private String reqArgDefltVal;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.struct_api_arg.respn_arg_id
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	private String respnArgId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.struct_api_arg.respn_arg_samp_val
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	private String respnArgSampVal;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.struct_api_arg.field_file_desc
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	private String fieldFileDesc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.struct_api_arg.calc_princ_id
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	private Integer calcPrincId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.struct_api_arg.value_range
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	private String valueRange;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.struct_api_arg.api_id
	 * 
	 * @return the value of opi.struct_api_arg.api_id
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public Integer getApiId() {
		return apiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.struct_api_arg.api_id
	 * 
	 * @param apiId the value for opi.struct_api_arg.api_id
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public void setApiId(Integer apiId) {
		this.apiId = apiId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.struct_api_arg.api_version
	 * 
	 * @return the value of opi.struct_api_arg.api_version
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public Integer getApiVersion() {
		return apiVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.struct_api_arg.api_version
	 * 
	 * @param apiVersion the value for opi.struct_api_arg.api_version
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public void setApiVersion(Integer apiVersion) {
		this.apiVersion = apiVersion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.struct_api_arg.field_alias
	 * 
	 * @return the value of opi.struct_api_arg.field_alias
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public String getFieldAlias() {
		return fieldAlias;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.struct_api_arg.field_alias
	 * 
	 * @param fieldAlias the value for opi.struct_api_arg.field_alias
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public void setFieldAlias(String fieldAlias) {
		this.fieldAlias = fieldAlias == null ? null : fieldAlias.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.struct_api_arg.field_name
	 * 
	 * @return the value of opi.struct_api_arg.field_name
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public String getFieldName() {
		return fieldName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.struct_api_arg.field_name
	 * 
	 * @param fieldName the value for opi.struct_api_arg.field_name
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public void setFieldName(String fieldName) {
		this.fieldName = fieldName == null ? null : fieldName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * opi.struct_api_arg.field_eff_stat
	 * 
	 * @return the value of opi.struct_api_arg.field_eff_stat
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public Integer getFieldEffStat() {
		return fieldEffStat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.struct_api_arg.field_eff_stat
	 * 
	 * @param fieldEffStat the value for opi.struct_api_arg.field_eff_stat
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public void setFieldEffStat(Integer fieldEffStat) {
		this.fieldEffStat = fieldEffStat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * opi.struct_api_arg.field_sorc_type
	 * 
	 * @return the value of opi.struct_api_arg.field_sorc_type
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public String getFieldSorcType() {
		return fieldSorcType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.struct_api_arg.field_sorc_type
	 * 
	 * @param fieldSorcType the value for opi.struct_api_arg.field_sorc_type
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public void setFieldSorcType(String fieldSorcType) {
		this.fieldSorcType = fieldSorcType == null ? null : fieldSorcType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * opi.struct_api_arg.field_targt_type
	 * 
	 * @return the value of opi.struct_api_arg.field_targt_type
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public String getFieldTargtType() {
		return fieldTargtType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.struct_api_arg.field_targt_type
	 * 
	 * @param fieldTargtType the value for opi.struct_api_arg.field_targt_type
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public void setFieldTargtType(String fieldTargtType) {
		this.fieldTargtType = fieldTargtType == null ? null : fieldTargtType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.struct_api_arg.field_title
	 * 
	 * @return the value of opi.struct_api_arg.field_title
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public String getFieldTitle() {
		return fieldTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.struct_api_arg.field_title
	 * 
	 * @param fieldTitle the value for opi.struct_api_arg.field_title
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public void setFieldTitle(String fieldTitle) {
		this.fieldTitle = fieldTitle == null ? null : fieldTitle.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * opi.struct_api_arg.sync_must_type
	 * 
	 * @return the value of opi.struct_api_arg.must_type
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public Integer getSyncMustType() {
		return syncMustType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.struct_api_arg.sync_must_type
	 * 
	 * @param mustType the value for opi.struct_api_arg.must_type
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public void setSyncMustType(Integer syncMustType) {
		this.syncMustType = syncMustType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * opi.struct_api_arg.sync_must_one_grp_id
	 * 
	 * @return the value of opi.struct_api_arg.sync_must_one_grp_id
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public Integer getSyncMustOneGrpId() {
		return syncMustOneGrpId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * opi.struct_api_arg.sync_must_one_grp_id
	 * 
	 * @param mustOneGrpId the value for opi.struct_api_arg.sync_must_one_grp_id
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public void setSyncMustOneGrpId(Integer syncMustOneGrpId) {
		this.syncMustOneGrpId = syncMustOneGrpId;
	}

	public Integer getAsynMustType() {
		return asynMustType;
	}

	public void setAsynMustType(Integer asynMustType) {
		this.asynMustType = asynMustType;
	}

	public Integer getAsynMustOneGrpId() {
		return asynMustOneGrpId;
	}

	public void setAsynMustOneGrpId(Integer asynMustOneGrpId) {
		this.asynMustOneGrpId = asynMustOneGrpId;
	}

	public Integer getRssMustType() {
		return rssMustType;
	}

	public void setRssMustType(Integer rssMustType) {
		this.rssMustType = rssMustType;
	}

	public Integer getRssMustOneGrpId() {
		return rssMustOneGrpId;
	}

	public void setRssMustOneGrpId(Integer rssMustOneGrpId) {
		this.rssMustOneGrpId = rssMustOneGrpId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.struct_api_arg.req_arg_id
	 * 
	 * @return the value of opi.struct_api_arg.req_arg_id
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public String getReqArgId() {
		return reqArgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.struct_api_arg.req_arg_id
	 * 
	 * @param reqArgId the value for opi.struct_api_arg.req_arg_id
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public void setReqArgId(String reqArgId) {
		this.reqArgId = reqArgId == null ? null : reqArgId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * opi.struct_api_arg.req_arg_deflt_val
	 * 
	 * @return the value of opi.struct_api_arg.req_arg_deflt_val
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public String getReqArgDefltVal() {
		return reqArgDefltVal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * opi.struct_api_arg.req_arg_deflt_val
	 * 
	 * @param reqArgDefltVal the value for opi.struct_api_arg.req_arg_deflt_val
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public void setReqArgDefltVal(String reqArgDefltVal) {
		this.reqArgDefltVal = reqArgDefltVal == null ? null : reqArgDefltVal.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.struct_api_arg.respn_arg_id
	 * 
	 * @return the value of opi.struct_api_arg.respn_arg_id
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public String getRespnArgId() {
		return respnArgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.struct_api_arg.respn_arg_id
	 * 
	 * @param respnArgId the value for opi.struct_api_arg.respn_arg_id
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public void setRespnArgId(String respnArgId) {
		this.respnArgId = respnArgId == null ? null : respnArgId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * opi.struct_api_arg.respn_arg_samp_val
	 * 
	 * @return the value of opi.struct_api_arg.respn_arg_samp_val
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public String getRespnArgSampVal() {
		return respnArgSampVal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * opi.struct_api_arg.respn_arg_samp_val
	 * 
	 * @param respnArgSampVal the value for opi.struct_api_arg.respn_arg_samp_val
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public void setRespnArgSampVal(String respnArgSampVal) {
		this.respnArgSampVal = respnArgSampVal == null ? null : respnArgSampVal.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * opi.struct_api_arg.field_file_desc
	 * 
	 * @return the value of opi.struct_api_arg.field_file_desc
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public String getFieldFileDesc() {
		return fieldFileDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.struct_api_arg.field_file_desc
	 * 
	 * @param fieldFileDesc the value for opi.struct_api_arg.field_file_desc
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public void setFieldFileDesc(String fieldFileDesc) {
		this.fieldFileDesc = fieldFileDesc == null ? null : fieldFileDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.struct_api_arg.calc_princ_id
	 * 
	 * @return the value of opi.struct_api_arg.calc_princ_id
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public Integer getCalcPrincId() {
		return calcPrincId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.struct_api_arg.calc_princ_id
	 * 
	 * @param calcPrincId the value for opi.struct_api_arg.calc_princ_id
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public void setCalcPrincId(Integer calcPrincId) {
		this.calcPrincId = calcPrincId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.struct_api_arg.value_range
	 * 
	 * @return the value of opi.struct_api_arg.value_range
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public String getValueRange() {
		return valueRange;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.struct_api_arg.value_range
	 * 
	 * @param valueRange the value for opi.struct_api_arg.value_range
	 * 
	 * @mbggenerated Wed Jun 15 14:40:17 CST 2016
	 */
	public void setValueRange(String valueRange) {
		this.valueRange = valueRange == null ? null : valueRange.trim();
	}
}