package com.teradata.openapi.access.biz.bean;

import java.io.Serializable;

public class CalcPrincCode implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 9223219446718067792L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column calc_princ_code.calc_princ_id
	 * 
	 * @mbggenerated Thu Apr 28 17:36:33 CST 2016
	 */
	private Integer calcPrincId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column calc_princ_code.calc_princ_desc
	 * 
	 * @mbggenerated Thu Apr 28 17:36:33 CST 2016
	 */
	private String calcPrincDesc;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column calc_princ_code.calc_formula
	 * 
	 * @mbggenerated Thu Apr 28 17:36:33 CST 2016
	 */
	private String calcFormula;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column calc_princ_code.subhd_type
	 * 
	 * @mbggenerated Thu Apr 28 17:36:33 CST 2016
	 */
	private String subhdType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column calc_princ_code.arg_form
	 * 
	 * @mbggenerated Thu Apr 28 17:36:33 CST 2016
	 */
	private String argForm;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column calc_princ_code.arg_samp
	 * 
	 * @mbggenerated Thu Apr 28 17:36:33 CST 2016
	 */
	private String argSamp;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column calc_princ_code.calc_princ_id
	 * 
	 * @return the value of calc_princ_code.calc_princ_id
	 * 
	 * @mbggenerated Thu Apr 28 17:36:33 CST 2016
	 */
	public Integer getCalcPrincId() {
		return calcPrincId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column calc_princ_code.calc_princ_id
	 * 
	 * @param calcPrincId the value for calc_princ_code.calc_princ_id
	 * 
	 * @mbggenerated Thu Apr 28 17:36:33 CST 2016
	 */
	public void setCalcPrincId(Integer calcPrincId) {
		this.calcPrincId = calcPrincId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column calc_princ_code.calc_princ_desc
	 * 
	 * @return the value of calc_princ_code.calc_princ_desc
	 * 
	 * @mbggenerated Thu Apr 28 17:36:33 CST 2016
	 */
	public String getCalcPrincDesc() {
		return calcPrincDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column calc_princ_code.calc_princ_desc
	 * 
	 * @param calcPrincDesc the value for calc_princ_code.calc_princ_desc
	 * 
	 * @mbggenerated Thu Apr 28 17:36:33 CST 2016
	 */
	public void setCalcPrincDesc(String calcPrincDesc) {
		this.calcPrincDesc = calcPrincDesc == null ? null : calcPrincDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column calc_princ_code.calc_formula
	 * 
	 * @return the value of calc_princ_code.calc_formula
	 * 
	 * @mbggenerated Thu Apr 28 17:36:33 CST 2016
	 */
	public String getCalcFormula() {
		return calcFormula;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column calc_princ_code.calc_formula
	 * 
	 * @param calcFormula the value for calc_princ_code.calc_formula
	 * 
	 * @mbggenerated Thu Apr 28 17:36:33 CST 2016
	 */
	public void setCalcFormula(String calcFormula) {
		this.calcFormula = calcFormula == null ? null : calcFormula.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column calc_princ_code.subhd_type
	 * 
	 * @return the value of calc_princ_code.subhd_type
	 * 
	 * @mbggenerated Thu Apr 28 17:36:33 CST 2016
	 */
	public String getSubhdType() {
		return subhdType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column calc_princ_code.subhd_type
	 * 
	 * @param subhdType the value for calc_princ_code.subhd_type
	 * 
	 * @mbggenerated Thu Apr 28 17:36:33 CST 2016
	 */
	public void setSubhdType(String subhdType) {
		this.subhdType = subhdType == null ? null : subhdType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column calc_princ_code.arg_form
	 * 
	 * @return the value of calc_princ_code.arg_form
	 * 
	 * @mbggenerated Thu Apr 28 17:36:33 CST 2016
	 */
	public String getArgForm() {
		return argForm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column calc_princ_code.arg_form
	 * 
	 * @param argForm the value for calc_princ_code.arg_form
	 * 
	 * @mbggenerated Thu Apr 28 17:36:33 CST 2016
	 */
	public void setArgForm(String argForm) {
		this.argForm = argForm == null ? null : argForm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column calc_princ_code.arg_samp
	 * 
	 * @return the value of calc_princ_code.arg_samp
	 * 
	 * @mbggenerated Thu Apr 28 17:36:33 CST 2016
	 */
	public String getArgSamp() {
		return argSamp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column calc_princ_code.arg_samp
	 * 
	 * @param argSamp the value for calc_princ_code.arg_samp
	 * 
	 * @mbggenerated Thu Apr 28 17:36:33 CST 2016
	 */
	public void setArgSamp(String argSamp) {
		this.argSamp = argSamp == null ? null : argSamp.trim();
	}
}