package com.teradata.openapi.access.biz.bean;

import java.io.Serializable;
import java.util.List;

public class UserGrpInfo implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = -2640556737952347195L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.user_grp_info.user_grp_id
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	private Integer userGrpId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.user_grp_info.user_grp_name
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	private String userGrpName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.user_grp_info.user_grp_desc
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	private String userGrpDesc;

	private List<UserInfo> userList;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.user_grp_info.user_grp_id
	 * 
	 * @return the value of opi.user_grp_info.user_grp_id
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public Integer getUserGrpId() {
		return userGrpId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.user_grp_info.user_grp_id
	 * 
	 * @param userGrpId the value for opi.user_grp_info.user_grp_id
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public void setUserGrpId(Integer userGrpId) {
		this.userGrpId = userGrpId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.user_grp_info.user_grp_name
	 * 
	 * @return the value of opi.user_grp_info.user_grp_name
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public String getUserGrpName() {
		return userGrpName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.user_grp_info.user_grp_name
	 * 
	 * @param userGrpName the value for opi.user_grp_info.user_grp_name
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public void setUserGrpName(String userGrpName) {
		this.userGrpName = userGrpName == null ? null : userGrpName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.user_grp_info.user_grp_desc
	 * 
	 * @return the value of opi.user_grp_info.user_grp_desc
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public String getUserGrpDesc() {
		return userGrpDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.user_grp_info.user_grp_desc
	 * 
	 * @param userGrpDesc the value for opi.user_grp_info.user_grp_desc
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public void setUserGrpDesc(String userGrpDesc) {
		this.userGrpDesc = userGrpDesc == null ? null : userGrpDesc.trim();
	}

	public List<UserInfo> getUserList() {
		return userList;
	}

	public void setUserList(List<UserInfo> userList) {
		this.userList = userList;
	}

}