package com.teradata.openapi.access.biz.bean;

import java.io.Serializable;
import java.util.Date;

public class UserInfo implements Serializable {

	/** serialVersionUID */
	private static final long serialVersionUID = 6121633407041553907L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.user_info.user_id
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	private Integer userId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.user_info.login_acct
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	private String loginAcct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.user_info.login_pwd
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	private String loginPwd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.user_info.user_name
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	private String userName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.user_info.user_stat
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	private String userStat;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.user_info.org_code
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	private Integer orgCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.user_info.email
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	private String email;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.user_info.phone
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	private String phone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.user_info.gender
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	private Integer gender;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.user_info.position
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	private String position;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.user_info.user_type
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	private Integer userType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.user_info.region_code
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	private String regionCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.user_info.city_code
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	private String cityCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.user_info.site_code
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	private String siteCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.user_info.ip_white_list
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	private String ipWhiteList;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.user_info.regist_persn
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	private String registPersn;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.user_info.regist_time
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	private Date registTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.user_info.user_grade
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	private Integer userGrade;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column opi.user_info.priority
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	private Integer priority;

	private Integer userGrpId;// 归属组

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.user_info.user_id
	 * 
	 * @return the value of opi.user_info.user_id
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.user_info.user_id
	 * 
	 * @param userId the value for opi.user_info.user_id
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.user_info.login_acct
	 * 
	 * @return the value of opi.user_info.login_acct
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public String getLoginAcct() {
		return loginAcct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.user_info.login_acct
	 * 
	 * @param loginAcct the value for opi.user_info.login_acct
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public void setLoginAcct(String loginAcct) {
		this.loginAcct = loginAcct == null ? null : loginAcct.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.user_info.login_pwd
	 * 
	 * @return the value of opi.user_info.login_pwd
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public String getLoginPwd() {
		return loginPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.user_info.login_pwd
	 * 
	 * @param loginPwd the value for opi.user_info.login_pwd
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public void setLoginPwd(String loginPwd) {
		this.loginPwd = loginPwd == null ? null : loginPwd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.user_info.user_name
	 * 
	 * @return the value of opi.user_info.user_name
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.user_info.user_name
	 * 
	 * @param userName the value for opi.user_info.user_name
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public void setUserName(String userName) {
		this.userName = userName == null ? null : userName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.user_info.user_stat
	 * 
	 * @return the value of opi.user_info.user_stat
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public String getUserStat() {
		return userStat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.user_info.user_stat
	 * 
	 * @param userStat the value for opi.user_info.user_stat
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public void setUserStat(String userStat) {
		this.userStat = userStat == null ? null : userStat.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.user_info.org_code
	 * 
	 * @return the value of opi.user_info.org_code
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public Integer getOrgCode() {
		return orgCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.user_info.org_code
	 * 
	 * @param orgCode the value for opi.user_info.org_code
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public void setOrgCode(Integer orgCode) {
		this.orgCode = orgCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.user_info.email
	 * 
	 * @return the value of opi.user_info.email
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.user_info.email
	 * 
	 * @param email the value for opi.user_info.email
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public void setEmail(String email) {
		this.email = email == null ? null : email.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.user_info.phone
	 * 
	 * @return the value of opi.user_info.phone
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.user_info.phone
	 * 
	 * @param phone the value for opi.user_info.phone
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public void setPhone(String phone) {
		this.phone = phone == null ? null : phone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.user_info.gender
	 * 
	 * @return the value of opi.user_info.gender
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public Integer getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.user_info.gender
	 * 
	 * @param gender the value for opi.user_info.gender
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public void setGender(Integer gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.user_info.position
	 * 
	 * @return the value of opi.user_info.position
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public String getPosition() {
		return position;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.user_info.position
	 * 
	 * @param position the value for opi.user_info.position
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public void setPosition(String position) {
		this.position = position == null ? null : position.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.user_info.user_type
	 * 
	 * @return the value of opi.user_info.user_type
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public Integer getUserType() {
		return userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.user_info.user_type
	 * 
	 * @param userType the value for opi.user_info.user_type
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public void setUserType(Integer userType) {
		this.userType = userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.user_info.region_code
	 * 
	 * @return the value of opi.user_info.region_code
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public String getRegionCode() {
		return regionCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.user_info.region_code
	 * 
	 * @param regionCode the value for opi.user_info.region_code
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public void setRegionCode(String regionCode) {
		this.regionCode = regionCode == null ? null : regionCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.user_info.city_code
	 * 
	 * @return the value of opi.user_info.city_code
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public String getCityCode() {
		return cityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.user_info.city_code
	 * 
	 * @param cityCode the value for opi.user_info.city_code
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public void setCityCode(String cityCode) {
		this.cityCode = cityCode == null ? null : cityCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.user_info.site_code
	 * 
	 * @return the value of opi.user_info.site_code
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public String getSiteCode() {
		return siteCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.user_info.site_code
	 * 
	 * @param siteCode the value for opi.user_info.site_code
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public void setSiteCode(String siteCode) {
		this.siteCode = siteCode == null ? null : siteCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.user_info.ip_white_list
	 * 
	 * @return the value of opi.user_info.ip_white_list
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public String getIpWhiteList() {
		return ipWhiteList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.user_info.ip_white_list
	 * 
	 * @param ipWhiteList the value for opi.user_info.ip_white_list
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public void setIpWhiteList(String ipWhiteList) {
		this.ipWhiteList = ipWhiteList == null ? null : ipWhiteList.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.user_info.regist_persn
	 * 
	 * @return the value of opi.user_info.regist_persn
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public String getRegistPersn() {
		return registPersn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.user_info.regist_persn
	 * 
	 * @param registPersn the value for opi.user_info.regist_persn
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public void setRegistPersn(String registPersn) {
		this.registPersn = registPersn == null ? null : registPersn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.user_info.regist_time
	 * 
	 * @return the value of opi.user_info.regist_time
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public Date getRegistTime() {
		return registTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.user_info.regist_time
	 * 
	 * @param registTime the value for opi.user_info.regist_time
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public void setRegistTime(Date registTime) {
		this.registTime = registTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.user_info.user_grade
	 * 
	 * @return the value of opi.user_info.user_grade
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public Integer getUserGrade() {
		return userGrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.user_info.user_grade
	 * 
	 * @param userGrade the value for opi.user_info.user_grade
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public void setUserGrade(Integer userGrade) {
		this.userGrade = userGrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column opi.user_info.priority
	 * 
	 * @return the value of opi.user_info.priority
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public Integer getPriority() {
		return priority;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column opi.user_info.priority
	 * 
	 * @param priority the value for opi.user_info.priority
	 * 
	 * @mbggenerated Thu Apr 28 14:20:14 CST 2016
	 */
	public void setPriority(Integer priority) {
		this.priority = priority;
	}

	public Integer getUserGrpId() {
		return userGrpId;
	}

	public void setUserGrpId(Integer userGrpId) {
		this.userGrpId = userGrpId;
	}

}