package com.teradata.portal.admin.subscribe.dao;

import java.util.List;
import java.util.Map;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.github.miemiedev.mybatis.paginator.domain.PageList;
import com.teradata.portal.admin.subscribe.pojo.ApiRssInfo;
import com.teradata.portal.admin.subscribe.pojo.ApiRssInfoExample;
import com.teradata.portal.web.sandbox.pojo.ApiInfo;

public interface ApiRssInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opi.api_rss_info
	 * 
	 * @mbggenerated Mon Jul 18 14:58:53 CST 2016
	 */
	int countByExample(ApiRssInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opi.api_rss_info
	 * 
	 * @mbggenerated Mon Jul 18 14:58:53 CST 2016
	 */
	int insert(ApiRssInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opi.api_rss_info
	 * 
	 * @mbggenerated Mon Jul 18 14:58:53 CST 2016
	 */
	List<ApiRssInfo> selectByExample(ApiRssInfoExample example);

	ApiRssInfo selectByPrimaryKey(Integer rssId);

	int updateByPrimaryKeySelective(ApiRssInfo record);

	PageList<ApiRssInfo> selectByExample(ApiRssInfoExample example, PageBounds pageBounds);

	ApiInfo queryApiInfoWithOption(Map<String, Object> paramMap);

}